local protobuf = protobuf
autoImport("xCmd_pb")
local xCmd_pb = xCmd_pb
autoImport("ProtoCommon_pb")
local ProtoCommon_pb = ProtoCommon_pb
autoImport("SceneItem_pb")
local SceneItem_pb = SceneItem_pb
module("SnowCmd_pb")
SNOWPARAM = protobuf.EnumDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_HEAD_QUERY_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_HEAD_LVUP_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_HEAD_ACTIVE_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_HEAD_MODE_CHANGE_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_HEAD_FASHION_SELECT_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_CROWN_ACTIVE_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOWMANUAL_QUERY_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOWMANUAL_UPDATE_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOWMANUAL_STONE_UPDATE_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_EQUIP_ENUM = protobuf.EnumValueDescriptor()
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_STONE_ENUM = protobuf.EnumValueDescriptor()
ESNOWMODE = protobuf.EnumDescriptor()
ESNOWMODE_ESNOW_MODE_MIN_ENUM = protobuf.EnumValueDescriptor()
ESNOWMODE_ESNOW_MODE_ATK_ENUM = protobuf.EnumValueDescriptor()
ESNOWMODE_ESNOW_MODE_DEF_ENUM = protobuf.EnumValueDescriptor()
ESNOWMODE_ESNOW_MODE_ELE_ENUM = protobuf.EnumValueDescriptor()
ESNOWEQUIPOPER = protobuf.EnumDescriptor()
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MIN_ENUM = protobuf.EnumValueDescriptor()
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_STORE_ENUM = protobuf.EnumValueDescriptor()
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_TAKEOUT_ENUM = protobuf.EnumValueDescriptor()
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MAX_ENUM = protobuf.EnumValueDescriptor()
ESNOWSTONEOPER = protobuf.EnumDescriptor()
ESNOWSTONEOPER_ESNOW_STONE_OPER_MIN_ENUM = protobuf.EnumValueDescriptor()
ESNOWSTONEOPER_ESNOW_STONE_OPER_STORE_ENUM = protobuf.EnumValueDescriptor()
ESNOWSTONEOPER_ESNOW_STONE_OPER_TAKEOUT_ENUM = protobuf.EnumValueDescriptor()
ESNOWSTONEOPER_ESNOW_STONE_OPER_LEVELUP_ENUM = protobuf.EnumValueDescriptor()
ESNOWSTONEOPER_ESNOW_STONE_OPER_MAX_ENUM = protobuf.EnumValueDescriptor()
SNOWMODEDATA = protobuf.Descriptor()
SNOWMODEDATA_MODE_FIELD = protobuf.FieldDescriptor()
SNOWMODEDATA_ACTIVATEIDS_FIELD = protobuf.FieldDescriptor()
SNOWFASHIONDATA = protobuf.Descriptor()
SNOWFASHIONDATA_POS_FIELD = protobuf.FieldDescriptor()
SNOWFASHIONDATA_USEID_FIELD = protobuf.FieldDescriptor()
SNOWFASHIONDATA_FASHIONIDS_FIELD = protobuf.FieldDescriptor()
SNOWCROWNDATA = protobuf.Descriptor()
SNOWCROWNDATA_IDS_FIELD = protobuf.FieldDescriptor()
SNOWDATA = protobuf.Descriptor()
SNOWDATA_BATCH_FIELD = protobuf.FieldDescriptor()
SNOWDATA_LEVEL_FIELD = protobuf.FieldDescriptor()
SNOWDATA_OPEN_FIELD = protobuf.FieldDescriptor()
SNOWDATA_USEMODE_FIELD = protobuf.FieldDescriptor()
SNOWDATA_MODEDATAS_FIELD = protobuf.FieldDescriptor()
SNOWDATA_FASHIONDATAS_FIELD = protobuf.FieldDescriptor()
SNOWDATA_CROWNDATA_FIELD = protobuf.FieldDescriptor()
SNOWHEADQUERYSNOWCMD = protobuf.Descriptor()
SNOWHEADQUERYSNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWHEADQUERYSNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWHEADQUERYSNOWCMD_GUID_FIELD = protobuf.FieldDescriptor()
SNOWHEADQUERYSNOWCMD_DATA_FIELD = protobuf.FieldDescriptor()
SNOWHEADLVUPSNOWCMD = protobuf.Descriptor()
SNOWHEADLVUPSNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWHEADLVUPSNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWHEADLVUPSNOWCMD_GUID_FIELD = protobuf.FieldDescriptor()
SNOWHEADACTIVESNOWCMD = protobuf.Descriptor()
SNOWHEADACTIVESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWHEADACTIVESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWHEADACTIVESNOWCMD_GUID_FIELD = protobuf.FieldDescriptor()
SNOWHEADACTIVESNOWCMD_ID_FIELD = protobuf.FieldDescriptor()
SNOWHEADMODECHANGESNOWCMD = protobuf.Descriptor()
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD = protobuf.FieldDescriptor()
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD = protobuf.FieldDescriptor()
SNOWHEADFASHIONSELECTSNOWCMD = protobuf.Descriptor()
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD = protobuf.FieldDescriptor()
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD = protobuf.FieldDescriptor()
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD = protobuf.FieldDescriptor()
SNOWCROWNACTIVESNOWCMD = protobuf.Descriptor()
SNOWCROWNACTIVESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWCROWNACTIVESNOWCMD_ID_FIELD = protobuf.FieldDescriptor()
SNOWPOS = protobuf.Descriptor()
SNOWPOS_ID_FIELD = protobuf.FieldDescriptor()
SNOWPOS_EQUIP_FIELD = protobuf.FieldDescriptor()
SNOWPOS_STONEIDS_FIELD = protobuf.FieldDescriptor()
SNOWSTONE = protobuf.Descriptor()
SNOWSTONE_ID_FIELD = protobuf.FieldDescriptor()
SNOWSTONE_LV_FIELD = protobuf.FieldDescriptor()
SNOWSTONE_ADVLV_FIELD = protobuf.FieldDescriptor()
SNOWSTONE_ADVEXP_FIELD = protobuf.FieldDescriptor()
SNOWSTONE_OVERFLOW_FIELD = protobuf.FieldDescriptor()
QUERYSNOWMANUALSNOWCMD = protobuf.Descriptor()
QUERYSNOWMANUALSNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
QUERYSNOWMANUALSNOWCMD_POS_FIELD = protobuf.FieldDescriptor()
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD = protobuf.FieldDescriptor()
SNOWMANUALUPDATESNOWCMD = protobuf.Descriptor()
SNOWMANUALUPDATESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD = protobuf.FieldDescriptor()
SNOWMANUALEQUIPUPDATESNOWCMD = protobuf.Descriptor()
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD = protobuf.FieldDescriptor()
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD = protobuf.FieldDescriptor()
SNOWMANUALSTONEUPDATESNOWCMD = protobuf.Descriptor()
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD = protobuf.FieldDescriptor()
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD = protobuf.FieldDescriptor()
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD = protobuf.FieldDescriptor()
OPERSNOWEQUIPSNOWCMD = protobuf.Descriptor()
OPERSNOWEQUIPSNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
OPERSNOWEQUIPSNOWCMD_OPER_FIELD = protobuf.FieldDescriptor()
OPERSNOWEQUIPSNOWCMD_POS_FIELD = protobuf.FieldDescriptor()
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD = protobuf.FieldDescriptor()
OPERSNOWSTONESNOWCMD = protobuf.Descriptor()
OPERSNOWSTONESNOWCMD_CMD_FIELD = protobuf.FieldDescriptor()
OPERSNOWSTONESNOWCMD_PARAM_FIELD = protobuf.FieldDescriptor()
OPERSNOWSTONESNOWCMD_OPER_FIELD = protobuf.FieldDescriptor()
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD = protobuf.FieldDescriptor()
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD = protobuf.FieldDescriptor()
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD = protobuf.FieldDescriptor()
SNOWPARAM_SNOWPARAM_SNOW_HEAD_QUERY_ENUM.name = "SNOWPARAM_SNOW_HEAD_QUERY"
SNOWPARAM_SNOWPARAM_SNOW_HEAD_QUERY_ENUM.index = 0
SNOWPARAM_SNOWPARAM_SNOW_HEAD_QUERY_ENUM.number = 1
SNOWPARAM_SNOWPARAM_SNOW_HEAD_LVUP_ENUM.name = "SNOWPARAM_SNOW_HEAD_LVUP"
SNOWPARAM_SNOWPARAM_SNOW_HEAD_LVUP_ENUM.index = 1
SNOWPARAM_SNOWPARAM_SNOW_HEAD_LVUP_ENUM.number = 2
SNOWPARAM_SNOWPARAM_SNOW_HEAD_ACTIVE_ENUM.name = "SNOWPARAM_SNOW_HEAD_ACTIVE"
SNOWPARAM_SNOWPARAM_SNOW_HEAD_ACTIVE_ENUM.index = 2
SNOWPARAM_SNOWPARAM_SNOW_HEAD_ACTIVE_ENUM.number = 3
SNOWPARAM_SNOWPARAM_SNOW_HEAD_MODE_CHANGE_ENUM.name = "SNOWPARAM_SNOW_HEAD_MODE_CHANGE"
SNOWPARAM_SNOWPARAM_SNOW_HEAD_MODE_CHANGE_ENUM.index = 3
SNOWPARAM_SNOWPARAM_SNOW_HEAD_MODE_CHANGE_ENUM.number = 4
SNOWPARAM_SNOWPARAM_SNOW_HEAD_FASHION_SELECT_ENUM.name = "SNOWPARAM_SNOW_HEAD_FASHION_SELECT"
SNOWPARAM_SNOWPARAM_SNOW_HEAD_FASHION_SELECT_ENUM.index = 4
SNOWPARAM_SNOWPARAM_SNOW_HEAD_FASHION_SELECT_ENUM.number = 5
SNOWPARAM_SNOWPARAM_SNOW_CROWN_ACTIVE_ENUM.name = "SNOWPARAM_SNOW_CROWN_ACTIVE"
SNOWPARAM_SNOWPARAM_SNOW_CROWN_ACTIVE_ENUM.index = 5
SNOWPARAM_SNOWPARAM_SNOW_CROWN_ACTIVE_ENUM.number = 6
SNOWPARAM_SNOWPARAM_SNOWMANUAL_QUERY_ENUM.name = "SNOWPARAM_SNOWMANUAL_QUERY"
SNOWPARAM_SNOWPARAM_SNOWMANUAL_QUERY_ENUM.index = 6
SNOWPARAM_SNOWPARAM_SNOWMANUAL_QUERY_ENUM.number = 7
SNOWPARAM_SNOWPARAM_SNOWMANUAL_UPDATE_ENUM.name = "SNOWPARAM_SNOWMANUAL_UPDATE"
SNOWPARAM_SNOWPARAM_SNOWMANUAL_UPDATE_ENUM.index = 7
SNOWPARAM_SNOWPARAM_SNOWMANUAL_UPDATE_ENUM.number = 8
SNOWPARAM_SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE_ENUM.name = "SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE"
SNOWPARAM_SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE_ENUM.index = 8
SNOWPARAM_SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE_ENUM.number = 9
SNOWPARAM_SNOWPARAM_SNOWMANUAL_STONE_UPDATE_ENUM.name = "SNOWPARAM_SNOWMANUAL_STONE_UPDATE"
SNOWPARAM_SNOWPARAM_SNOWMANUAL_STONE_UPDATE_ENUM.index = 9
SNOWPARAM_SNOWPARAM_SNOWMANUAL_STONE_UPDATE_ENUM.number = 10
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_EQUIP_ENUM.name = "SNOWPARAM_SNOWMANUAL_OPER_EQUIP"
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_EQUIP_ENUM.index = 10
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_EQUIP_ENUM.number = 11
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_STONE_ENUM.name = "SNOWPARAM_SNOWMANUAL_OPER_STONE"
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_STONE_ENUM.index = 11
SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_STONE_ENUM.number = 12
SNOWPARAM.name = "SnowParam"
SNOWPARAM.full_name = ".Cmd.SnowParam"
SNOWPARAM.values = {
  SNOWPARAM_SNOWPARAM_SNOW_HEAD_QUERY_ENUM,
  SNOWPARAM_SNOWPARAM_SNOW_HEAD_LVUP_ENUM,
  SNOWPARAM_SNOWPARAM_SNOW_HEAD_ACTIVE_ENUM,
  SNOWPARAM_SNOWPARAM_SNOW_HEAD_MODE_CHANGE_ENUM,
  SNOWPARAM_SNOWPARAM_SNOW_HEAD_FASHION_SELECT_ENUM,
  SNOWPARAM_SNOWPARAM_SNOW_CROWN_ACTIVE_ENUM,
  SNOWPARAM_SNOWPARAM_SNOWMANUAL_QUERY_ENUM,
  SNOWPARAM_SNOWPARAM_SNOWMANUAL_UPDATE_ENUM,
  SNOWPARAM_SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE_ENUM,
  SNOWPARAM_SNOWPARAM_SNOWMANUAL_STONE_UPDATE_ENUM,
  SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_EQUIP_ENUM,
  SNOWPARAM_SNOWPARAM_SNOWMANUAL_OPER_STONE_ENUM
}
ESNOWMODE_ESNOW_MODE_MIN_ENUM.name = "ESNOW_MODE_MIN"
ESNOWMODE_ESNOW_MODE_MIN_ENUM.index = 0
ESNOWMODE_ESNOW_MODE_MIN_ENUM.number = 0
ESNOWMODE_ESNOW_MODE_ATK_ENUM.name = "ESNOW_MODE_ATK"
ESNOWMODE_ESNOW_MODE_ATK_ENUM.index = 1
ESNOWMODE_ESNOW_MODE_ATK_ENUM.number = 1
ESNOWMODE_ESNOW_MODE_DEF_ENUM.name = "ESNOW_MODE_DEF"
ESNOWMODE_ESNOW_MODE_DEF_ENUM.index = 2
ESNOWMODE_ESNOW_MODE_DEF_ENUM.number = 2
ESNOWMODE_ESNOW_MODE_ELE_ENUM.name = "ESNOW_MODE_ELE"
ESNOWMODE_ESNOW_MODE_ELE_ENUM.index = 3
ESNOWMODE_ESNOW_MODE_ELE_ENUM.number = 3
ESNOWMODE.name = "ESnowMode"
ESNOWMODE.full_name = ".Cmd.ESnowMode"
ESNOWMODE.values = {
  ESNOWMODE_ESNOW_MODE_MIN_ENUM,
  ESNOWMODE_ESNOW_MODE_ATK_ENUM,
  ESNOWMODE_ESNOW_MODE_DEF_ENUM,
  ESNOWMODE_ESNOW_MODE_ELE_ENUM
}
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MIN_ENUM.name = "ESNOW_EQUIP_OPER_MIN"
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MIN_ENUM.index = 0
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MIN_ENUM.number = 0
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_STORE_ENUM.name = "ESNOW_EQUIP_OPER_STORE"
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_STORE_ENUM.index = 1
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_STORE_ENUM.number = 1
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_TAKEOUT_ENUM.name = "ESNOW_EQUIP_OPER_TAKEOUT"
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_TAKEOUT_ENUM.index = 2
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_TAKEOUT_ENUM.number = 2
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MAX_ENUM.name = "ESNOW_EQUIP_OPER_MAX"
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MAX_ENUM.index = 3
ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MAX_ENUM.number = 3
ESNOWEQUIPOPER.name = "ESnowEquipOper"
ESNOWEQUIPOPER.full_name = ".Cmd.ESnowEquipOper"
ESNOWEQUIPOPER.values = {
  ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MIN_ENUM,
  ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_STORE_ENUM,
  ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_TAKEOUT_ENUM,
  ESNOWEQUIPOPER_ESNOW_EQUIP_OPER_MAX_ENUM
}
ESNOWSTONEOPER_ESNOW_STONE_OPER_MIN_ENUM.name = "ESNOW_STONE_OPER_MIN"
ESNOWSTONEOPER_ESNOW_STONE_OPER_MIN_ENUM.index = 0
ESNOWSTONEOPER_ESNOW_STONE_OPER_MIN_ENUM.number = 0
ESNOWSTONEOPER_ESNOW_STONE_OPER_STORE_ENUM.name = "ESNOW_STONE_OPER_STORE"
ESNOWSTONEOPER_ESNOW_STONE_OPER_STORE_ENUM.index = 1
ESNOWSTONEOPER_ESNOW_STONE_OPER_STORE_ENUM.number = 1
ESNOWSTONEOPER_ESNOW_STONE_OPER_TAKEOUT_ENUM.name = "ESNOW_STONE_OPER_TAKEOUT"
ESNOWSTONEOPER_ESNOW_STONE_OPER_TAKEOUT_ENUM.index = 2
ESNOWSTONEOPER_ESNOW_STONE_OPER_TAKEOUT_ENUM.number = 2
ESNOWSTONEOPER_ESNOW_STONE_OPER_LEVELUP_ENUM.name = "ESNOW_STONE_OPER_LEVELUP"
ESNOWSTONEOPER_ESNOW_STONE_OPER_LEVELUP_ENUM.index = 3
ESNOWSTONEOPER_ESNOW_STONE_OPER_LEVELUP_ENUM.number = 3
ESNOWSTONEOPER_ESNOW_STONE_OPER_MAX_ENUM.name = "ESNOW_STONE_OPER_MAX"
ESNOWSTONEOPER_ESNOW_STONE_OPER_MAX_ENUM.index = 4
ESNOWSTONEOPER_ESNOW_STONE_OPER_MAX_ENUM.number = 4
ESNOWSTONEOPER.name = "ESnowStoneOper"
ESNOWSTONEOPER.full_name = ".Cmd.ESnowStoneOper"
ESNOWSTONEOPER.values = {
  ESNOWSTONEOPER_ESNOW_STONE_OPER_MIN_ENUM,
  ESNOWSTONEOPER_ESNOW_STONE_OPER_STORE_ENUM,
  ESNOWSTONEOPER_ESNOW_STONE_OPER_TAKEOUT_ENUM,
  ESNOWSTONEOPER_ESNOW_STONE_OPER_LEVELUP_ENUM,
  ESNOWSTONEOPER_ESNOW_STONE_OPER_MAX_ENUM
}
SNOWMODEDATA_MODE_FIELD.name = "mode"
SNOWMODEDATA_MODE_FIELD.full_name = ".Cmd.SnowModeData.mode"
SNOWMODEDATA_MODE_FIELD.number = 1
SNOWMODEDATA_MODE_FIELD.index = 0
SNOWMODEDATA_MODE_FIELD.label = 1
SNOWMODEDATA_MODE_FIELD.has_default_value = true
SNOWMODEDATA_MODE_FIELD.default_value = 0
SNOWMODEDATA_MODE_FIELD.enum_type = ESNOWMODE
SNOWMODEDATA_MODE_FIELD.type = 14
SNOWMODEDATA_MODE_FIELD.cpp_type = 8
SNOWMODEDATA_ACTIVATEIDS_FIELD.name = "activateids"
SNOWMODEDATA_ACTIVATEIDS_FIELD.full_name = ".Cmd.SnowModeData.activateids"
SNOWMODEDATA_ACTIVATEIDS_FIELD.number = 2
SNOWMODEDATA_ACTIVATEIDS_FIELD.index = 1
SNOWMODEDATA_ACTIVATEIDS_FIELD.label = 3
SNOWMODEDATA_ACTIVATEIDS_FIELD.has_default_value = false
SNOWMODEDATA_ACTIVATEIDS_FIELD.default_value = {}
SNOWMODEDATA_ACTIVATEIDS_FIELD.type = 13
SNOWMODEDATA_ACTIVATEIDS_FIELD.cpp_type = 3
SNOWMODEDATA.name = "SnowModeData"
SNOWMODEDATA.full_name = ".Cmd.SnowModeData"
SNOWMODEDATA.nested_types = {}
SNOWMODEDATA.enum_types = {}
SNOWMODEDATA.fields = {
  SNOWMODEDATA_MODE_FIELD,
  SNOWMODEDATA_ACTIVATEIDS_FIELD
}
SNOWMODEDATA.is_extendable = false
SNOWMODEDATA.extensions = {}
SNOWFASHIONDATA_POS_FIELD.name = "pos"
SNOWFASHIONDATA_POS_FIELD.full_name = ".Cmd.SnowFashionData.pos"
SNOWFASHIONDATA_POS_FIELD.number = 1
SNOWFASHIONDATA_POS_FIELD.index = 0
SNOWFASHIONDATA_POS_FIELD.label = 1
SNOWFASHIONDATA_POS_FIELD.has_default_value = false
SNOWFASHIONDATA_POS_FIELD.default_value = 0
SNOWFASHIONDATA_POS_FIELD.type = 13
SNOWFASHIONDATA_POS_FIELD.cpp_type = 3
SNOWFASHIONDATA_USEID_FIELD.name = "useid"
SNOWFASHIONDATA_USEID_FIELD.full_name = ".Cmd.SnowFashionData.useid"
SNOWFASHIONDATA_USEID_FIELD.number = 2
SNOWFASHIONDATA_USEID_FIELD.index = 1
SNOWFASHIONDATA_USEID_FIELD.label = 1
SNOWFASHIONDATA_USEID_FIELD.has_default_value = false
SNOWFASHIONDATA_USEID_FIELD.default_value = 0
SNOWFASHIONDATA_USEID_FIELD.type = 13
SNOWFASHIONDATA_USEID_FIELD.cpp_type = 3
SNOWFASHIONDATA_FASHIONIDS_FIELD.name = "fashionids"
SNOWFASHIONDATA_FASHIONIDS_FIELD.full_name = ".Cmd.SnowFashionData.fashionids"
SNOWFASHIONDATA_FASHIONIDS_FIELD.number = 3
SNOWFASHIONDATA_FASHIONIDS_FIELD.index = 2
SNOWFASHIONDATA_FASHIONIDS_FIELD.label = 3
SNOWFASHIONDATA_FASHIONIDS_FIELD.has_default_value = false
SNOWFASHIONDATA_FASHIONIDS_FIELD.default_value = {}
SNOWFASHIONDATA_FASHIONIDS_FIELD.type = 13
SNOWFASHIONDATA_FASHIONIDS_FIELD.cpp_type = 3
SNOWFASHIONDATA.name = "SnowFashionData"
SNOWFASHIONDATA.full_name = ".Cmd.SnowFashionData"
SNOWFASHIONDATA.nested_types = {}
SNOWFASHIONDATA.enum_types = {}
SNOWFASHIONDATA.fields = {
  SNOWFASHIONDATA_POS_FIELD,
  SNOWFASHIONDATA_USEID_FIELD,
  SNOWFASHIONDATA_FASHIONIDS_FIELD
}
SNOWFASHIONDATA.is_extendable = false
SNOWFASHIONDATA.extensions = {}
SNOWCROWNDATA_IDS_FIELD.name = "ids"
SNOWCROWNDATA_IDS_FIELD.full_name = ".Cmd.SnowCrownData.ids"
SNOWCROWNDATA_IDS_FIELD.number = 1
SNOWCROWNDATA_IDS_FIELD.index = 0
SNOWCROWNDATA_IDS_FIELD.label = 3
SNOWCROWNDATA_IDS_FIELD.has_default_value = false
SNOWCROWNDATA_IDS_FIELD.default_value = {}
SNOWCROWNDATA_IDS_FIELD.type = 13
SNOWCROWNDATA_IDS_FIELD.cpp_type = 3
SNOWCROWNDATA.name = "SnowCrownData"
SNOWCROWNDATA.full_name = ".Cmd.SnowCrownData"
SNOWCROWNDATA.nested_types = {}
SNOWCROWNDATA.enum_types = {}
SNOWCROWNDATA.fields = {
  SNOWCROWNDATA_IDS_FIELD
}
SNOWCROWNDATA.is_extendable = false
SNOWCROWNDATA.extensions = {}
SNOWDATA_BATCH_FIELD.name = "batch"
SNOWDATA_BATCH_FIELD.full_name = ".Cmd.SnowData.batch"
SNOWDATA_BATCH_FIELD.number = 1
SNOWDATA_BATCH_FIELD.index = 0
SNOWDATA_BATCH_FIELD.label = 1
SNOWDATA_BATCH_FIELD.has_default_value = false
SNOWDATA_BATCH_FIELD.default_value = 0
SNOWDATA_BATCH_FIELD.type = 13
SNOWDATA_BATCH_FIELD.cpp_type = 3
SNOWDATA_LEVEL_FIELD.name = "level"
SNOWDATA_LEVEL_FIELD.full_name = ".Cmd.SnowData.level"
SNOWDATA_LEVEL_FIELD.number = 2
SNOWDATA_LEVEL_FIELD.index = 1
SNOWDATA_LEVEL_FIELD.label = 1
SNOWDATA_LEVEL_FIELD.has_default_value = false
SNOWDATA_LEVEL_FIELD.default_value = 0
SNOWDATA_LEVEL_FIELD.type = 13
SNOWDATA_LEVEL_FIELD.cpp_type = 3
SNOWDATA_OPEN_FIELD.name = "open"
SNOWDATA_OPEN_FIELD.full_name = ".Cmd.SnowData.open"
SNOWDATA_OPEN_FIELD.number = 3
SNOWDATA_OPEN_FIELD.index = 2
SNOWDATA_OPEN_FIELD.label = 1
SNOWDATA_OPEN_FIELD.has_default_value = true
SNOWDATA_OPEN_FIELD.default_value = false
SNOWDATA_OPEN_FIELD.type = 8
SNOWDATA_OPEN_FIELD.cpp_type = 7
SNOWDATA_USEMODE_FIELD.name = "usemode"
SNOWDATA_USEMODE_FIELD.full_name = ".Cmd.SnowData.usemode"
SNOWDATA_USEMODE_FIELD.number = 4
SNOWDATA_USEMODE_FIELD.index = 3
SNOWDATA_USEMODE_FIELD.label = 1
SNOWDATA_USEMODE_FIELD.has_default_value = false
SNOWDATA_USEMODE_FIELD.default_value = nil
SNOWDATA_USEMODE_FIELD.enum_type = ESNOWMODE
SNOWDATA_USEMODE_FIELD.type = 14
SNOWDATA_USEMODE_FIELD.cpp_type = 8
SNOWDATA_MODEDATAS_FIELD.name = "modedatas"
SNOWDATA_MODEDATAS_FIELD.full_name = ".Cmd.SnowData.modedatas"
SNOWDATA_MODEDATAS_FIELD.number = 5
SNOWDATA_MODEDATAS_FIELD.index = 4
SNOWDATA_MODEDATAS_FIELD.label = 3
SNOWDATA_MODEDATAS_FIELD.has_default_value = false
SNOWDATA_MODEDATAS_FIELD.default_value = {}
SNOWDATA_MODEDATAS_FIELD.message_type = SNOWMODEDATA
SNOWDATA_MODEDATAS_FIELD.type = 11
SNOWDATA_MODEDATAS_FIELD.cpp_type = 10
SNOWDATA_FASHIONDATAS_FIELD.name = "fashiondatas"
SNOWDATA_FASHIONDATAS_FIELD.full_name = ".Cmd.SnowData.fashiondatas"
SNOWDATA_FASHIONDATAS_FIELD.number = 6
SNOWDATA_FASHIONDATAS_FIELD.index = 5
SNOWDATA_FASHIONDATAS_FIELD.label = 3
SNOWDATA_FASHIONDATAS_FIELD.has_default_value = false
SNOWDATA_FASHIONDATAS_FIELD.default_value = {}
SNOWDATA_FASHIONDATAS_FIELD.message_type = SNOWFASHIONDATA
SNOWDATA_FASHIONDATAS_FIELD.type = 11
SNOWDATA_FASHIONDATAS_FIELD.cpp_type = 10
SNOWDATA_CROWNDATA_FIELD.name = "crowndata"
SNOWDATA_CROWNDATA_FIELD.full_name = ".Cmd.SnowData.crowndata"
SNOWDATA_CROWNDATA_FIELD.number = 7
SNOWDATA_CROWNDATA_FIELD.index = 6
SNOWDATA_CROWNDATA_FIELD.label = 1
SNOWDATA_CROWNDATA_FIELD.has_default_value = false
SNOWDATA_CROWNDATA_FIELD.default_value = nil
SNOWDATA_CROWNDATA_FIELD.message_type = SNOWCROWNDATA
SNOWDATA_CROWNDATA_FIELD.type = 11
SNOWDATA_CROWNDATA_FIELD.cpp_type = 10
SNOWDATA.name = "SnowData"
SNOWDATA.full_name = ".Cmd.SnowData"
SNOWDATA.nested_types = {}
SNOWDATA.enum_types = {}
SNOWDATA.fields = {
  SNOWDATA_BATCH_FIELD,
  SNOWDATA_LEVEL_FIELD,
  SNOWDATA_OPEN_FIELD,
  SNOWDATA_USEMODE_FIELD,
  SNOWDATA_MODEDATAS_FIELD,
  SNOWDATA_FASHIONDATAS_FIELD,
  SNOWDATA_CROWNDATA_FIELD
}
SNOWDATA.is_extendable = false
SNOWDATA.extensions = {}
SNOWHEADQUERYSNOWCMD_CMD_FIELD.name = "cmd"
SNOWHEADQUERYSNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowHeadQuerySnowCmd.cmd"
SNOWHEADQUERYSNOWCMD_CMD_FIELD.number = 1
SNOWHEADQUERYSNOWCMD_CMD_FIELD.index = 0
SNOWHEADQUERYSNOWCMD_CMD_FIELD.label = 1
SNOWHEADQUERYSNOWCMD_CMD_FIELD.has_default_value = true
SNOWHEADQUERYSNOWCMD_CMD_FIELD.default_value = 85
SNOWHEADQUERYSNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWHEADQUERYSNOWCMD_CMD_FIELD.type = 14
SNOWHEADQUERYSNOWCMD_CMD_FIELD.cpp_type = 8
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.name = "param"
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowHeadQuerySnowCmd.param"
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.number = 2
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.index = 1
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.label = 1
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.has_default_value = true
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.default_value = 1
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.type = 14
SNOWHEADQUERYSNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWHEADQUERYSNOWCMD_GUID_FIELD.name = "guid"
SNOWHEADQUERYSNOWCMD_GUID_FIELD.full_name = ".Cmd.SnowHeadQuerySnowCmd.guid"
SNOWHEADQUERYSNOWCMD_GUID_FIELD.number = 3
SNOWHEADQUERYSNOWCMD_GUID_FIELD.index = 2
SNOWHEADQUERYSNOWCMD_GUID_FIELD.label = 1
SNOWHEADQUERYSNOWCMD_GUID_FIELD.has_default_value = false
SNOWHEADQUERYSNOWCMD_GUID_FIELD.default_value = ""
SNOWHEADQUERYSNOWCMD_GUID_FIELD.type = 9
SNOWHEADQUERYSNOWCMD_GUID_FIELD.cpp_type = 9
SNOWHEADQUERYSNOWCMD_DATA_FIELD.name = "data"
SNOWHEADQUERYSNOWCMD_DATA_FIELD.full_name = ".Cmd.SnowHeadQuerySnowCmd.data"
SNOWHEADQUERYSNOWCMD_DATA_FIELD.number = 4
SNOWHEADQUERYSNOWCMD_DATA_FIELD.index = 3
SNOWHEADQUERYSNOWCMD_DATA_FIELD.label = 1
SNOWHEADQUERYSNOWCMD_DATA_FIELD.has_default_value = false
SNOWHEADQUERYSNOWCMD_DATA_FIELD.default_value = nil
SNOWHEADQUERYSNOWCMD_DATA_FIELD.message_type = SNOWDATA
SNOWHEADQUERYSNOWCMD_DATA_FIELD.type = 11
SNOWHEADQUERYSNOWCMD_DATA_FIELD.cpp_type = 10
SNOWHEADQUERYSNOWCMD.name = "SnowHeadQuerySnowCmd"
SNOWHEADQUERYSNOWCMD.full_name = ".Cmd.SnowHeadQuerySnowCmd"
SNOWHEADQUERYSNOWCMD.nested_types = {}
SNOWHEADQUERYSNOWCMD.enum_types = {}
SNOWHEADQUERYSNOWCMD.fields = {
  SNOWHEADQUERYSNOWCMD_CMD_FIELD,
  SNOWHEADQUERYSNOWCMD_PARAM_FIELD,
  SNOWHEADQUERYSNOWCMD_GUID_FIELD,
  SNOWHEADQUERYSNOWCMD_DATA_FIELD
}
SNOWHEADQUERYSNOWCMD.is_extendable = false
SNOWHEADQUERYSNOWCMD.extensions = {}
SNOWHEADLVUPSNOWCMD_CMD_FIELD.name = "cmd"
SNOWHEADLVUPSNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowHeadLvupSnowCmd.cmd"
SNOWHEADLVUPSNOWCMD_CMD_FIELD.number = 1
SNOWHEADLVUPSNOWCMD_CMD_FIELD.index = 0
SNOWHEADLVUPSNOWCMD_CMD_FIELD.label = 1
SNOWHEADLVUPSNOWCMD_CMD_FIELD.has_default_value = true
SNOWHEADLVUPSNOWCMD_CMD_FIELD.default_value = 85
SNOWHEADLVUPSNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWHEADLVUPSNOWCMD_CMD_FIELD.type = 14
SNOWHEADLVUPSNOWCMD_CMD_FIELD.cpp_type = 8
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.name = "param"
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowHeadLvupSnowCmd.param"
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.number = 2
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.index = 1
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.label = 1
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.has_default_value = true
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.default_value = 2
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.type = 14
SNOWHEADLVUPSNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWHEADLVUPSNOWCMD_GUID_FIELD.name = "guid"
SNOWHEADLVUPSNOWCMD_GUID_FIELD.full_name = ".Cmd.SnowHeadLvupSnowCmd.guid"
SNOWHEADLVUPSNOWCMD_GUID_FIELD.number = 3
SNOWHEADLVUPSNOWCMD_GUID_FIELD.index = 2
SNOWHEADLVUPSNOWCMD_GUID_FIELD.label = 1
SNOWHEADLVUPSNOWCMD_GUID_FIELD.has_default_value = false
SNOWHEADLVUPSNOWCMD_GUID_FIELD.default_value = ""
SNOWHEADLVUPSNOWCMD_GUID_FIELD.type = 9
SNOWHEADLVUPSNOWCMD_GUID_FIELD.cpp_type = 9
SNOWHEADLVUPSNOWCMD.name = "SnowHeadLvupSnowCmd"
SNOWHEADLVUPSNOWCMD.full_name = ".Cmd.SnowHeadLvupSnowCmd"
SNOWHEADLVUPSNOWCMD.nested_types = {}
SNOWHEADLVUPSNOWCMD.enum_types = {}
SNOWHEADLVUPSNOWCMD.fields = {
  SNOWHEADLVUPSNOWCMD_CMD_FIELD,
  SNOWHEADLVUPSNOWCMD_PARAM_FIELD,
  SNOWHEADLVUPSNOWCMD_GUID_FIELD
}
SNOWHEADLVUPSNOWCMD.is_extendable = false
SNOWHEADLVUPSNOWCMD.extensions = {}
SNOWHEADACTIVESNOWCMD_CMD_FIELD.name = "cmd"
SNOWHEADACTIVESNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowHeadActiveSnowCmd.cmd"
SNOWHEADACTIVESNOWCMD_CMD_FIELD.number = 1
SNOWHEADACTIVESNOWCMD_CMD_FIELD.index = 0
SNOWHEADACTIVESNOWCMD_CMD_FIELD.label = 1
SNOWHEADACTIVESNOWCMD_CMD_FIELD.has_default_value = true
SNOWHEADACTIVESNOWCMD_CMD_FIELD.default_value = 85
SNOWHEADACTIVESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWHEADACTIVESNOWCMD_CMD_FIELD.type = 14
SNOWHEADACTIVESNOWCMD_CMD_FIELD.cpp_type = 8
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.name = "param"
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowHeadActiveSnowCmd.param"
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.number = 2
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.index = 1
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.label = 1
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.has_default_value = true
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.default_value = 3
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.type = 14
SNOWHEADACTIVESNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWHEADACTIVESNOWCMD_GUID_FIELD.name = "guid"
SNOWHEADACTIVESNOWCMD_GUID_FIELD.full_name = ".Cmd.SnowHeadActiveSnowCmd.guid"
SNOWHEADACTIVESNOWCMD_GUID_FIELD.number = 3
SNOWHEADACTIVESNOWCMD_GUID_FIELD.index = 2
SNOWHEADACTIVESNOWCMD_GUID_FIELD.label = 1
SNOWHEADACTIVESNOWCMD_GUID_FIELD.has_default_value = false
SNOWHEADACTIVESNOWCMD_GUID_FIELD.default_value = ""
SNOWHEADACTIVESNOWCMD_GUID_FIELD.type = 9
SNOWHEADACTIVESNOWCMD_GUID_FIELD.cpp_type = 9
SNOWHEADACTIVESNOWCMD_ID_FIELD.name = "id"
SNOWHEADACTIVESNOWCMD_ID_FIELD.full_name = ".Cmd.SnowHeadActiveSnowCmd.id"
SNOWHEADACTIVESNOWCMD_ID_FIELD.number = 4
SNOWHEADACTIVESNOWCMD_ID_FIELD.index = 3
SNOWHEADACTIVESNOWCMD_ID_FIELD.label = 1
SNOWHEADACTIVESNOWCMD_ID_FIELD.has_default_value = false
SNOWHEADACTIVESNOWCMD_ID_FIELD.default_value = 0
SNOWHEADACTIVESNOWCMD_ID_FIELD.type = 13
SNOWHEADACTIVESNOWCMD_ID_FIELD.cpp_type = 3
SNOWHEADACTIVESNOWCMD.name = "SnowHeadActiveSnowCmd"
SNOWHEADACTIVESNOWCMD.full_name = ".Cmd.SnowHeadActiveSnowCmd"
SNOWHEADACTIVESNOWCMD.nested_types = {}
SNOWHEADACTIVESNOWCMD.enum_types = {}
SNOWHEADACTIVESNOWCMD.fields = {
  SNOWHEADACTIVESNOWCMD_CMD_FIELD,
  SNOWHEADACTIVESNOWCMD_PARAM_FIELD,
  SNOWHEADACTIVESNOWCMD_GUID_FIELD,
  SNOWHEADACTIVESNOWCMD_ID_FIELD
}
SNOWHEADACTIVESNOWCMD.is_extendable = false
SNOWHEADACTIVESNOWCMD.extensions = {}
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.name = "cmd"
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowHeadModeChangeSnowCmd.cmd"
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.number = 1
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.index = 0
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.label = 1
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.has_default_value = true
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.default_value = 85
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.type = 14
SNOWHEADMODECHANGESNOWCMD_CMD_FIELD.cpp_type = 8
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.name = "param"
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowHeadModeChangeSnowCmd.param"
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.number = 2
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.index = 1
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.label = 1
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.has_default_value = true
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.default_value = 4
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.type = 14
SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.name = "guid"
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.full_name = ".Cmd.SnowHeadModeChangeSnowCmd.guid"
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.number = 3
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.index = 2
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.label = 1
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.has_default_value = false
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.default_value = ""
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.type = 9
SNOWHEADMODECHANGESNOWCMD_GUID_FIELD.cpp_type = 9
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.name = "mode"
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.full_name = ".Cmd.SnowHeadModeChangeSnowCmd.mode"
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.number = 4
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.index = 3
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.label = 1
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.has_default_value = false
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.default_value = nil
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.enum_type = ESNOWMODE
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.type = 14
SNOWHEADMODECHANGESNOWCMD_MODE_FIELD.cpp_type = 8
SNOWHEADMODECHANGESNOWCMD.name = "SnowHeadModeChangeSnowCmd"
SNOWHEADMODECHANGESNOWCMD.full_name = ".Cmd.SnowHeadModeChangeSnowCmd"
SNOWHEADMODECHANGESNOWCMD.nested_types = {}
SNOWHEADMODECHANGESNOWCMD.enum_types = {}
SNOWHEADMODECHANGESNOWCMD.fields = {
  SNOWHEADMODECHANGESNOWCMD_CMD_FIELD,
  SNOWHEADMODECHANGESNOWCMD_PARAM_FIELD,
  SNOWHEADMODECHANGESNOWCMD_GUID_FIELD,
  SNOWHEADMODECHANGESNOWCMD_MODE_FIELD
}
SNOWHEADMODECHANGESNOWCMD.is_extendable = false
SNOWHEADMODECHANGESNOWCMD.extensions = {}
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.name = "cmd"
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowHeadFashionSelectSnowCmd.cmd"
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.number = 1
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.index = 0
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.label = 1
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.has_default_value = true
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.default_value = 85
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.type = 14
SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD.cpp_type = 8
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.name = "param"
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowHeadFashionSelectSnowCmd.param"
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.number = 2
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.index = 1
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.label = 1
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.has_default_value = true
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.default_value = 5
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.type = 14
SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.name = "guid"
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.full_name = ".Cmd.SnowHeadFashionSelectSnowCmd.guid"
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.number = 3
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.index = 2
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.label = 1
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.has_default_value = false
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.default_value = ""
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.type = 9
SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD.cpp_type = 9
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.name = "pos"
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.full_name = ".Cmd.SnowHeadFashionSelectSnowCmd.pos"
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.number = 4
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.index = 3
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.label = 1
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.has_default_value = false
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.default_value = 0
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.type = 13
SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD.cpp_type = 3
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.name = "index"
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.full_name = ".Cmd.SnowHeadFashionSelectSnowCmd.index"
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.number = 5
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.index = 4
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.label = 1
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.has_default_value = false
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.default_value = 0
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.type = 13
SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD.cpp_type = 3
SNOWHEADFASHIONSELECTSNOWCMD.name = "SnowHeadFashionSelectSnowCmd"
SNOWHEADFASHIONSELECTSNOWCMD.full_name = ".Cmd.SnowHeadFashionSelectSnowCmd"
SNOWHEADFASHIONSELECTSNOWCMD.nested_types = {}
SNOWHEADFASHIONSELECTSNOWCMD.enum_types = {}
SNOWHEADFASHIONSELECTSNOWCMD.fields = {
  SNOWHEADFASHIONSELECTSNOWCMD_CMD_FIELD,
  SNOWHEADFASHIONSELECTSNOWCMD_PARAM_FIELD,
  SNOWHEADFASHIONSELECTSNOWCMD_GUID_FIELD,
  SNOWHEADFASHIONSELECTSNOWCMD_POS_FIELD,
  SNOWHEADFASHIONSELECTSNOWCMD_INDEX_FIELD
}
SNOWHEADFASHIONSELECTSNOWCMD.is_extendable = false
SNOWHEADFASHIONSELECTSNOWCMD.extensions = {}
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.name = "cmd"
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowCrownActiveSnowCmd.cmd"
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.number = 1
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.index = 0
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.label = 1
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.has_default_value = true
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.default_value = 85
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.type = 14
SNOWCROWNACTIVESNOWCMD_CMD_FIELD.cpp_type = 8
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.name = "param"
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowCrownActiveSnowCmd.param"
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.number = 2
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.index = 1
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.label = 1
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.has_default_value = true
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.default_value = 6
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.type = 14
SNOWCROWNACTIVESNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWCROWNACTIVESNOWCMD_ID_FIELD.name = "id"
SNOWCROWNACTIVESNOWCMD_ID_FIELD.full_name = ".Cmd.SnowCrownActiveSnowCmd.id"
SNOWCROWNACTIVESNOWCMD_ID_FIELD.number = 3
SNOWCROWNACTIVESNOWCMD_ID_FIELD.index = 2
SNOWCROWNACTIVESNOWCMD_ID_FIELD.label = 1
SNOWCROWNACTIVESNOWCMD_ID_FIELD.has_default_value = false
SNOWCROWNACTIVESNOWCMD_ID_FIELD.default_value = 0
SNOWCROWNACTIVESNOWCMD_ID_FIELD.type = 13
SNOWCROWNACTIVESNOWCMD_ID_FIELD.cpp_type = 3
SNOWCROWNACTIVESNOWCMD.name = "SnowCrownActiveSnowCmd"
SNOWCROWNACTIVESNOWCMD.full_name = ".Cmd.SnowCrownActiveSnowCmd"
SNOWCROWNACTIVESNOWCMD.nested_types = {}
SNOWCROWNACTIVESNOWCMD.enum_types = {}
SNOWCROWNACTIVESNOWCMD.fields = {
  SNOWCROWNACTIVESNOWCMD_CMD_FIELD,
  SNOWCROWNACTIVESNOWCMD_PARAM_FIELD,
  SNOWCROWNACTIVESNOWCMD_ID_FIELD
}
SNOWCROWNACTIVESNOWCMD.is_extendable = false
SNOWCROWNACTIVESNOWCMD.extensions = {}
SNOWPOS_ID_FIELD.name = "id"
SNOWPOS_ID_FIELD.full_name = ".Cmd.SnowPos.id"
SNOWPOS_ID_FIELD.number = 1
SNOWPOS_ID_FIELD.index = 0
SNOWPOS_ID_FIELD.label = 1
SNOWPOS_ID_FIELD.has_default_value = false
SNOWPOS_ID_FIELD.default_value = 0
SNOWPOS_ID_FIELD.type = 13
SNOWPOS_ID_FIELD.cpp_type = 3
SNOWPOS_EQUIP_FIELD.name = "equip"
SNOWPOS_EQUIP_FIELD.full_name = ".Cmd.SnowPos.equip"
SNOWPOS_EQUIP_FIELD.number = 2
SNOWPOS_EQUIP_FIELD.index = 1
SNOWPOS_EQUIP_FIELD.label = 1
SNOWPOS_EQUIP_FIELD.has_default_value = false
SNOWPOS_EQUIP_FIELD.default_value = nil
SNOWPOS_EQUIP_FIELD.message_type = SceneItem_pb.ITEMDATA
SNOWPOS_EQUIP_FIELD.type = 11
SNOWPOS_EQUIP_FIELD.cpp_type = 10
SNOWPOS_STONEIDS_FIELD.name = "stoneids"
SNOWPOS_STONEIDS_FIELD.full_name = ".Cmd.SnowPos.stoneids"
SNOWPOS_STONEIDS_FIELD.number = 3
SNOWPOS_STONEIDS_FIELD.index = 2
SNOWPOS_STONEIDS_FIELD.label = 3
SNOWPOS_STONEIDS_FIELD.has_default_value = false
SNOWPOS_STONEIDS_FIELD.default_value = {}
SNOWPOS_STONEIDS_FIELD.type = 13
SNOWPOS_STONEIDS_FIELD.cpp_type = 3
SNOWPOS.name = "SnowPos"
SNOWPOS.full_name = ".Cmd.SnowPos"
SNOWPOS.nested_types = {}
SNOWPOS.enum_types = {}
SNOWPOS.fields = {
  SNOWPOS_ID_FIELD,
  SNOWPOS_EQUIP_FIELD,
  SNOWPOS_STONEIDS_FIELD
}
SNOWPOS.is_extendable = false
SNOWPOS.extensions = {}
SNOWSTONE_ID_FIELD.name = "id"
SNOWSTONE_ID_FIELD.full_name = ".Cmd.SnowStone.id"
SNOWSTONE_ID_FIELD.number = 1
SNOWSTONE_ID_FIELD.index = 0
SNOWSTONE_ID_FIELD.label = 1
SNOWSTONE_ID_FIELD.has_default_value = false
SNOWSTONE_ID_FIELD.default_value = 0
SNOWSTONE_ID_FIELD.type = 13
SNOWSTONE_ID_FIELD.cpp_type = 3
SNOWSTONE_LV_FIELD.name = "lv"
SNOWSTONE_LV_FIELD.full_name = ".Cmd.SnowStone.lv"
SNOWSTONE_LV_FIELD.number = 2
SNOWSTONE_LV_FIELD.index = 1
SNOWSTONE_LV_FIELD.label = 1
SNOWSTONE_LV_FIELD.has_default_value = false
SNOWSTONE_LV_FIELD.default_value = 0
SNOWSTONE_LV_FIELD.type = 13
SNOWSTONE_LV_FIELD.cpp_type = 3
SNOWSTONE_ADVLV_FIELD.name = "advlv"
SNOWSTONE_ADVLV_FIELD.full_name = ".Cmd.SnowStone.advlv"
SNOWSTONE_ADVLV_FIELD.number = 3
SNOWSTONE_ADVLV_FIELD.index = 2
SNOWSTONE_ADVLV_FIELD.label = 1
SNOWSTONE_ADVLV_FIELD.has_default_value = false
SNOWSTONE_ADVLV_FIELD.default_value = 0
SNOWSTONE_ADVLV_FIELD.type = 13
SNOWSTONE_ADVLV_FIELD.cpp_type = 3
SNOWSTONE_ADVEXP_FIELD.name = "advexp"
SNOWSTONE_ADVEXP_FIELD.full_name = ".Cmd.SnowStone.advexp"
SNOWSTONE_ADVEXP_FIELD.number = 4
SNOWSTONE_ADVEXP_FIELD.index = 3
SNOWSTONE_ADVEXP_FIELD.label = 1
SNOWSTONE_ADVEXP_FIELD.has_default_value = false
SNOWSTONE_ADVEXP_FIELD.default_value = 0
SNOWSTONE_ADVEXP_FIELD.type = 13
SNOWSTONE_ADVEXP_FIELD.cpp_type = 3
SNOWSTONE_OVERFLOW_FIELD.name = "overflow"
SNOWSTONE_OVERFLOW_FIELD.full_name = ".Cmd.SnowStone.overflow"
SNOWSTONE_OVERFLOW_FIELD.number = 5
SNOWSTONE_OVERFLOW_FIELD.index = 4
SNOWSTONE_OVERFLOW_FIELD.label = 1
SNOWSTONE_OVERFLOW_FIELD.has_default_value = false
SNOWSTONE_OVERFLOW_FIELD.default_value = 0
SNOWSTONE_OVERFLOW_FIELD.type = 13
SNOWSTONE_OVERFLOW_FIELD.cpp_type = 3
SNOWSTONE.name = "SnowStone"
SNOWSTONE.full_name = ".Cmd.SnowStone"
SNOWSTONE.nested_types = {}
SNOWSTONE.enum_types = {}
SNOWSTONE.fields = {
  SNOWSTONE_ID_FIELD,
  SNOWSTONE_LV_FIELD,
  SNOWSTONE_ADVLV_FIELD,
  SNOWSTONE_ADVEXP_FIELD,
  SNOWSTONE_OVERFLOW_FIELD
}
SNOWSTONE.is_extendable = false
SNOWSTONE.extensions = {}
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.name = "cmd"
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.full_name = ".Cmd.QuerySnowManualSnowCmd.cmd"
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.number = 1
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.index = 0
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.label = 1
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.has_default_value = true
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.default_value = 85
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.type = 14
QUERYSNOWMANUALSNOWCMD_CMD_FIELD.cpp_type = 8
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.name = "param"
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.full_name = ".Cmd.QuerySnowManualSnowCmd.param"
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.number = 2
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.index = 1
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.label = 1
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.has_default_value = true
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.default_value = 7
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.type = 14
QUERYSNOWMANUALSNOWCMD_PARAM_FIELD.cpp_type = 8
QUERYSNOWMANUALSNOWCMD_POS_FIELD.name = "pos"
QUERYSNOWMANUALSNOWCMD_POS_FIELD.full_name = ".Cmd.QuerySnowManualSnowCmd.pos"
QUERYSNOWMANUALSNOWCMD_POS_FIELD.number = 3
QUERYSNOWMANUALSNOWCMD_POS_FIELD.index = 2
QUERYSNOWMANUALSNOWCMD_POS_FIELD.label = 3
QUERYSNOWMANUALSNOWCMD_POS_FIELD.has_default_value = false
QUERYSNOWMANUALSNOWCMD_POS_FIELD.default_value = {}
QUERYSNOWMANUALSNOWCMD_POS_FIELD.message_type = SNOWPOS
QUERYSNOWMANUALSNOWCMD_POS_FIELD.type = 11
QUERYSNOWMANUALSNOWCMD_POS_FIELD.cpp_type = 10
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.name = "stone_book"
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.full_name = ".Cmd.QuerySnowManualSnowCmd.stone_book"
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.number = 4
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.index = 3
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.label = 3
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.has_default_value = false
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.default_value = {}
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.message_type = SNOWSTONE
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.type = 11
QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD.cpp_type = 10
QUERYSNOWMANUALSNOWCMD.name = "QuerySnowManualSnowCmd"
QUERYSNOWMANUALSNOWCMD.full_name = ".Cmd.QuerySnowManualSnowCmd"
QUERYSNOWMANUALSNOWCMD.nested_types = {}
QUERYSNOWMANUALSNOWCMD.enum_types = {}
QUERYSNOWMANUALSNOWCMD.fields = {
  QUERYSNOWMANUALSNOWCMD_CMD_FIELD,
  QUERYSNOWMANUALSNOWCMD_PARAM_FIELD,
  QUERYSNOWMANUALSNOWCMD_POS_FIELD,
  QUERYSNOWMANUALSNOWCMD_STONE_BOOK_FIELD
}
QUERYSNOWMANUALSNOWCMD.is_extendable = false
QUERYSNOWMANUALSNOWCMD.extensions = {}
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.name = "cmd"
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowManualUpdateSnowCmd.cmd"
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.number = 1
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.index = 0
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.label = 1
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.has_default_value = true
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.default_value = 85
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.type = 14
SNOWMANUALUPDATESNOWCMD_CMD_FIELD.cpp_type = 8
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.name = "param"
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowManualUpdateSnowCmd.param"
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.number = 2
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.index = 1
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.label = 1
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.has_default_value = true
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.default_value = 8
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.type = 14
SNOWMANUALUPDATESNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.name = "updates"
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.full_name = ".Cmd.SnowManualUpdateSnowCmd.updates"
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.number = 4
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.index = 2
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.label = 3
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.has_default_value = false
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.default_value = {}
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.message_type = SNOWSTONE
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.type = 11
SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD.cpp_type = 10
SNOWMANUALUPDATESNOWCMD.name = "SnowManualUpdateSnowCmd"
SNOWMANUALUPDATESNOWCMD.full_name = ".Cmd.SnowManualUpdateSnowCmd"
SNOWMANUALUPDATESNOWCMD.nested_types = {}
SNOWMANUALUPDATESNOWCMD.enum_types = {}
SNOWMANUALUPDATESNOWCMD.fields = {
  SNOWMANUALUPDATESNOWCMD_CMD_FIELD,
  SNOWMANUALUPDATESNOWCMD_PARAM_FIELD,
  SNOWMANUALUPDATESNOWCMD_UPDATES_FIELD
}
SNOWMANUALUPDATESNOWCMD.is_extendable = false
SNOWMANUALUPDATESNOWCMD.extensions = {}
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.name = "cmd"
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowManualEquipUpdateSnowCmd.cmd"
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.number = 1
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.index = 0
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.label = 1
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.has_default_value = true
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.default_value = 85
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.type = 14
SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD.cpp_type = 8
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.name = "param"
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowManualEquipUpdateSnowCmd.param"
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.number = 2
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.index = 1
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.label = 1
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.has_default_value = true
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.default_value = 9
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.type = 14
SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.name = "pos"
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.full_name = ".Cmd.SnowManualEquipUpdateSnowCmd.pos"
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.number = 3
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.index = 2
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.label = 1
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.has_default_value = false
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.default_value = 0
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.type = 13
SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD.cpp_type = 3
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.name = "update"
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.full_name = ".Cmd.SnowManualEquipUpdateSnowCmd.update"
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.number = 4
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.index = 3
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.label = 1
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.has_default_value = false
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.default_value = nil
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.message_type = SceneItem_pb.ITEMDATA
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.type = 11
SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD.cpp_type = 10
SNOWMANUALEQUIPUPDATESNOWCMD.name = "SnowManualEquipUpdateSnowCmd"
SNOWMANUALEQUIPUPDATESNOWCMD.full_name = ".Cmd.SnowManualEquipUpdateSnowCmd"
SNOWMANUALEQUIPUPDATESNOWCMD.nested_types = {}
SNOWMANUALEQUIPUPDATESNOWCMD.enum_types = {}
SNOWMANUALEQUIPUPDATESNOWCMD.fields = {
  SNOWMANUALEQUIPUPDATESNOWCMD_CMD_FIELD,
  SNOWMANUALEQUIPUPDATESNOWCMD_PARAM_FIELD,
  SNOWMANUALEQUIPUPDATESNOWCMD_POS_FIELD,
  SNOWMANUALEQUIPUPDATESNOWCMD_UPDATE_FIELD
}
SNOWMANUALEQUIPUPDATESNOWCMD.is_extendable = false
SNOWMANUALEQUIPUPDATESNOWCMD.extensions = {}
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.name = "cmd"
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.full_name = ".Cmd.SnowManualStoneUpdateSnowCmd.cmd"
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.number = 1
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.index = 0
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.label = 1
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.has_default_value = true
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.default_value = 85
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.type = 14
SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD.cpp_type = 8
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.name = "param"
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.full_name = ".Cmd.SnowManualStoneUpdateSnowCmd.param"
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.number = 2
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.index = 1
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.label = 1
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.has_default_value = true
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.default_value = 10
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.type = 14
SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD.cpp_type = 8
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.name = "equip_pos"
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.full_name = ".Cmd.SnowManualStoneUpdateSnowCmd.equip_pos"
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.number = 3
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.index = 2
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.label = 1
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.has_default_value = false
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.default_value = 0
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.type = 13
SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD.cpp_type = 3
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.name = "stone_pos"
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.full_name = ".Cmd.SnowManualStoneUpdateSnowCmd.stone_pos"
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.number = 4
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.index = 3
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.label = 1
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.has_default_value = false
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.default_value = 0
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.type = 13
SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD.cpp_type = 3
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.name = "update"
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.full_name = ".Cmd.SnowManualStoneUpdateSnowCmd.update"
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.number = 5
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.index = 4
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.label = 1
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.has_default_value = false
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.default_value = 0
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.type = 13
SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD.cpp_type = 3
SNOWMANUALSTONEUPDATESNOWCMD.name = "SnowManualStoneUpdateSnowCmd"
SNOWMANUALSTONEUPDATESNOWCMD.full_name = ".Cmd.SnowManualStoneUpdateSnowCmd"
SNOWMANUALSTONEUPDATESNOWCMD.nested_types = {}
SNOWMANUALSTONEUPDATESNOWCMD.enum_types = {}
SNOWMANUALSTONEUPDATESNOWCMD.fields = {
  SNOWMANUALSTONEUPDATESNOWCMD_CMD_FIELD,
  SNOWMANUALSTONEUPDATESNOWCMD_PARAM_FIELD,
  SNOWMANUALSTONEUPDATESNOWCMD_EQUIP_POS_FIELD,
  SNOWMANUALSTONEUPDATESNOWCMD_STONE_POS_FIELD,
  SNOWMANUALSTONEUPDATESNOWCMD_UPDATE_FIELD
}
SNOWMANUALSTONEUPDATESNOWCMD.is_extendable = false
SNOWMANUALSTONEUPDATESNOWCMD.extensions = {}
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.name = "cmd"
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.full_name = ".Cmd.OperSnowEquipSnowCmd.cmd"
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.number = 1
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.index = 0
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.label = 1
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.has_default_value = true
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.default_value = 85
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.type = 14
OPERSNOWEQUIPSNOWCMD_CMD_FIELD.cpp_type = 8
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.name = "param"
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.full_name = ".Cmd.OperSnowEquipSnowCmd.param"
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.number = 2
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.index = 1
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.label = 1
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.has_default_value = true
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.default_value = 11
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.type = 14
OPERSNOWEQUIPSNOWCMD_PARAM_FIELD.cpp_type = 8
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.name = "oper"
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.full_name = ".Cmd.OperSnowEquipSnowCmd.oper"
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.number = 3
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.index = 2
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.label = 1
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.has_default_value = false
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.default_value = nil
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.enum_type = ESNOWEQUIPOPER
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.type = 14
OPERSNOWEQUIPSNOWCMD_OPER_FIELD.cpp_type = 8
OPERSNOWEQUIPSNOWCMD_POS_FIELD.name = "pos"
OPERSNOWEQUIPSNOWCMD_POS_FIELD.full_name = ".Cmd.OperSnowEquipSnowCmd.pos"
OPERSNOWEQUIPSNOWCMD_POS_FIELD.number = 4
OPERSNOWEQUIPSNOWCMD_POS_FIELD.index = 3
OPERSNOWEQUIPSNOWCMD_POS_FIELD.label = 1
OPERSNOWEQUIPSNOWCMD_POS_FIELD.has_default_value = false
OPERSNOWEQUIPSNOWCMD_POS_FIELD.default_value = 0
OPERSNOWEQUIPSNOWCMD_POS_FIELD.type = 13
OPERSNOWEQUIPSNOWCMD_POS_FIELD.cpp_type = 3
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.name = "equip_guid"
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.full_name = ".Cmd.OperSnowEquipSnowCmd.equip_guid"
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.number = 5
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.index = 4
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.label = 1
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.has_default_value = false
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.default_value = ""
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.type = 9
OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD.cpp_type = 9
OPERSNOWEQUIPSNOWCMD.name = "OperSnowEquipSnowCmd"
OPERSNOWEQUIPSNOWCMD.full_name = ".Cmd.OperSnowEquipSnowCmd"
OPERSNOWEQUIPSNOWCMD.nested_types = {}
OPERSNOWEQUIPSNOWCMD.enum_types = {}
OPERSNOWEQUIPSNOWCMD.fields = {
  OPERSNOWEQUIPSNOWCMD_CMD_FIELD,
  OPERSNOWEQUIPSNOWCMD_PARAM_FIELD,
  OPERSNOWEQUIPSNOWCMD_OPER_FIELD,
  OPERSNOWEQUIPSNOWCMD_POS_FIELD,
  OPERSNOWEQUIPSNOWCMD_EQUIP_GUID_FIELD
}
OPERSNOWEQUIPSNOWCMD.is_extendable = false
OPERSNOWEQUIPSNOWCMD.extensions = {}
OPERSNOWSTONESNOWCMD_CMD_FIELD.name = "cmd"
OPERSNOWSTONESNOWCMD_CMD_FIELD.full_name = ".Cmd.OperSnowStoneSnowCmd.cmd"
OPERSNOWSTONESNOWCMD_CMD_FIELD.number = 1
OPERSNOWSTONESNOWCMD_CMD_FIELD.index = 0
OPERSNOWSTONESNOWCMD_CMD_FIELD.label = 1
OPERSNOWSTONESNOWCMD_CMD_FIELD.has_default_value = true
OPERSNOWSTONESNOWCMD_CMD_FIELD.default_value = 85
OPERSNOWSTONESNOWCMD_CMD_FIELD.enum_type = XCMD_PB_COMMAND
OPERSNOWSTONESNOWCMD_CMD_FIELD.type = 14
OPERSNOWSTONESNOWCMD_CMD_FIELD.cpp_type = 8
OPERSNOWSTONESNOWCMD_PARAM_FIELD.name = "param"
OPERSNOWSTONESNOWCMD_PARAM_FIELD.full_name = ".Cmd.OperSnowStoneSnowCmd.param"
OPERSNOWSTONESNOWCMD_PARAM_FIELD.number = 2
OPERSNOWSTONESNOWCMD_PARAM_FIELD.index = 1
OPERSNOWSTONESNOWCMD_PARAM_FIELD.label = 1
OPERSNOWSTONESNOWCMD_PARAM_FIELD.has_default_value = true
OPERSNOWSTONESNOWCMD_PARAM_FIELD.default_value = 12
OPERSNOWSTONESNOWCMD_PARAM_FIELD.enum_type = SNOWPARAM
OPERSNOWSTONESNOWCMD_PARAM_FIELD.type = 14
OPERSNOWSTONESNOWCMD_PARAM_FIELD.cpp_type = 8
OPERSNOWSTONESNOWCMD_OPER_FIELD.name = "oper"
OPERSNOWSTONESNOWCMD_OPER_FIELD.full_name = ".Cmd.OperSnowStoneSnowCmd.oper"
OPERSNOWSTONESNOWCMD_OPER_FIELD.number = 3
OPERSNOWSTONESNOWCMD_OPER_FIELD.index = 2
OPERSNOWSTONESNOWCMD_OPER_FIELD.label = 1
OPERSNOWSTONESNOWCMD_OPER_FIELD.has_default_value = false
OPERSNOWSTONESNOWCMD_OPER_FIELD.default_value = nil
OPERSNOWSTONESNOWCMD_OPER_FIELD.enum_type = ESNOWSTONEOPER
OPERSNOWSTONESNOWCMD_OPER_FIELD.type = 14
OPERSNOWSTONESNOWCMD_OPER_FIELD.cpp_type = 8
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.name = "equip_pos"
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.full_name = ".Cmd.OperSnowStoneSnowCmd.equip_pos"
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.number = 4
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.index = 3
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.label = 1
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.has_default_value = false
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.default_value = 0
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.type = 13
OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD.cpp_type = 3
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.name = "stone_pos"
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.full_name = ".Cmd.OperSnowStoneSnowCmd.stone_pos"
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.number = 5
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.index = 4
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.label = 1
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.has_default_value = false
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.default_value = 0
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.type = 13
OPERSNOWSTONESNOWCMD_STONE_POS_FIELD.cpp_type = 3
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.name = "stone_id"
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.full_name = ".Cmd.OperSnowStoneSnowCmd.stone_id"
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.number = 6
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.index = 5
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.label = 1
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.has_default_value = false
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.default_value = 0
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.type = 13
OPERSNOWSTONESNOWCMD_STONE_ID_FIELD.cpp_type = 3
OPERSNOWSTONESNOWCMD.name = "OperSnowStoneSnowCmd"
OPERSNOWSTONESNOWCMD.full_name = ".Cmd.OperSnowStoneSnowCmd"
OPERSNOWSTONESNOWCMD.nested_types = {}
OPERSNOWSTONESNOWCMD.enum_types = {}
OPERSNOWSTONESNOWCMD.fields = {
  OPERSNOWSTONESNOWCMD_CMD_FIELD,
  OPERSNOWSTONESNOWCMD_PARAM_FIELD,
  OPERSNOWSTONESNOWCMD_OPER_FIELD,
  OPERSNOWSTONESNOWCMD_EQUIP_POS_FIELD,
  OPERSNOWSTONESNOWCMD_STONE_POS_FIELD,
  OPERSNOWSTONESNOWCMD_STONE_ID_FIELD
}
OPERSNOWSTONESNOWCMD.is_extendable = false
OPERSNOWSTONESNOWCMD.extensions = {}
ESNOW_EQUIP_OPER_MAX = 3
ESNOW_EQUIP_OPER_MIN = 0
ESNOW_EQUIP_OPER_STORE = 1
ESNOW_EQUIP_OPER_TAKEOUT = 2
ESNOW_MODE_ATK = 1
ESNOW_MODE_DEF = 2
ESNOW_MODE_ELE = 3
ESNOW_MODE_MIN = 0
ESNOW_STONE_OPER_LEVELUP = 3
ESNOW_STONE_OPER_MAX = 4
ESNOW_STONE_OPER_MIN = 0
ESNOW_STONE_OPER_STORE = 1
ESNOW_STONE_OPER_TAKEOUT = 2
OperSnowEquipSnowCmd = protobuf.Message(OPERSNOWEQUIPSNOWCMD)
OperSnowStoneSnowCmd = protobuf.Message(OPERSNOWSTONESNOWCMD)
QuerySnowManualSnowCmd = protobuf.Message(QUERYSNOWMANUALSNOWCMD)
SNOWPARAM_SNOWMANUAL_EQUIP_UPDATE = 9
SNOWPARAM_SNOWMANUAL_OPER_EQUIP = 11
SNOWPARAM_SNOWMANUAL_OPER_STONE = 12
SNOWPARAM_SNOWMANUAL_QUERY = 7
SNOWPARAM_SNOWMANUAL_STONE_UPDATE = 10
SNOWPARAM_SNOWMANUAL_UPDATE = 8
SNOWPARAM_SNOW_CROWN_ACTIVE = 6
SNOWPARAM_SNOW_HEAD_ACTIVE = 3
SNOWPARAM_SNOW_HEAD_FASHION_SELECT = 5
SNOWPARAM_SNOW_HEAD_LVUP = 2
SNOWPARAM_SNOW_HEAD_MODE_CHANGE = 4
SNOWPARAM_SNOW_HEAD_QUERY = 1
SnowCrownActiveSnowCmd = protobuf.Message(SNOWCROWNACTIVESNOWCMD)
SnowCrownData = protobuf.Message(SNOWCROWNDATA)
SnowData = protobuf.Message(SNOWDATA)
SnowFashionData = protobuf.Message(SNOWFASHIONDATA)
SnowHeadActiveSnowCmd = protobuf.Message(SNOWHEADACTIVESNOWCMD)
SnowHeadFashionSelectSnowCmd = protobuf.Message(SNOWHEADFASHIONSELECTSNOWCMD)
SnowHeadLvupSnowCmd = protobuf.Message(SNOWHEADLVUPSNOWCMD)
SnowHeadModeChangeSnowCmd = protobuf.Message(SNOWHEADMODECHANGESNOWCMD)
SnowHeadQuerySnowCmd = protobuf.Message(SNOWHEADQUERYSNOWCMD)
SnowManualEquipUpdateSnowCmd = protobuf.Message(SNOWMANUALEQUIPUPDATESNOWCMD)
SnowManualStoneUpdateSnowCmd = protobuf.Message(SNOWMANUALSTONEUPDATESNOWCMD)
SnowManualUpdateSnowCmd = protobuf.Message(SNOWMANUALUPDATESNOWCMD)
SnowModeData = protobuf.Message(SNOWMODEDATA)
SnowPos = protobuf.Message(SNOWPOS)
SnowStone = protobuf.Message(SNOWSTONE)
