Table_SpaceTimeIllusionSummon_t = {
  minidefine = {
    {
      AtkRate = 0.8,
      DefRate = 1,
      LifeRate = 0.72,
      MAtkRate = 0.8,
      MDefRate = 1,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.85,
      DefRate = 1.06,
      LifeRate = 0.77,
      MAtkRate = 0.85,
      MDefRate = 1.06,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.9,
      DefRate = 1.13,
      LifeRate = 0.81,
      MAtkRate = 0.9,
      MDefRate = 1.13,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.95,
      DefRate = 1.19,
      LifeRate = 0.86,
      MAtkRate = 0.95,
      MDefRate = 1.19,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1.25,
      LifeRate = 0.9,
      MAtkRate = 1,
      MDefRate = 1.25,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.05,
      DefRate = 1.31,
      LifeRate = 0.95,
      MAtkRate = 1.05,
      MDefRate = 1.31,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.38,
      LifeRate = 0.99,
      MAtkRate = 1.1,
      MDefRate = 1.38,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.15,
      DefRate = 1.44,
      LifeRate = 1.04,
      MAtkRate = 1.15,
      MDefRate = 1.44,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.2,
      DefRate = 1.5,
      LifeRate = 1.08,
      MAtkRate = 1.2,
      MDefRate = 1.5,
      MonsterGroup = 33,
      MonsterLevel = 85,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.8,
      DefRate = 1,
      LifeRate = 0.84,
      MAtkRate = 0.8,
      MDefRate = 1,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.85,
      DefRate = 1.06,
      LifeRate = 0.89,
      MAtkRate = 0.85,
      MDefRate = 1.06,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.9,
      DefRate = 1.13,
      LifeRate = 0.95,
      MAtkRate = 0.9,
      MDefRate = 1.13,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.95,
      DefRate = 1.19,
      LifeRate = 1,
      MAtkRate = 0.95,
      MDefRate = 1.19,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1.25,
      LifeRate = 1.05,
      MAtkRate = 1,
      MDefRate = 1.25,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.05,
      DefRate = 1.31,
      LifeRate = 1.1,
      MAtkRate = 1.05,
      MDefRate = 1.31,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.38,
      LifeRate = 1.16,
      MAtkRate = 1.1,
      MDefRate = 1.38,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.15,
      DefRate = 1.44,
      LifeRate = 1.21,
      MAtkRate = 1.15,
      MDefRate = 1.44,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.2,
      DefRate = 1.5,
      LifeRate = 1.26,
      MAtkRate = 1.2,
      MDefRate = 1.5,
      MonsterGroup = 33,
      MonsterLevel = 100,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.72,
      DefRate = 1,
      LifeRate = 0.8,
      MAtkRate = 0.72,
      MDefRate = 1,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.77,
      DefRate = 1.06,
      LifeRate = 0.85,
      MAtkRate = 0.77,
      MDefRate = 1.06,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.81,
      DefRate = 1.13,
      LifeRate = 0.9,
      MAtkRate = 0.81,
      MDefRate = 1.13,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.86,
      DefRate = 1.19,
      LifeRate = 0.95,
      MAtkRate = 0.86,
      MDefRate = 1.19,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.9,
      DefRate = 1.25,
      LifeRate = 1,
      MAtkRate = 0.9,
      MDefRate = 1.25,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.95,
      DefRate = 1.31,
      LifeRate = 1.05,
      MAtkRate = 0.95,
      MDefRate = 1.31,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.99,
      DefRate = 1.38,
      LifeRate = 1.1,
      MAtkRate = 0.99,
      MDefRate = 1.38,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.04,
      DefRate = 1.44,
      LifeRate = 1.15,
      MAtkRate = 1.04,
      MDefRate = 1.44,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.08,
      DefRate = 1.5,
      LifeRate = 1.2,
      MAtkRate = 1.08,
      MDefRate = 1.5,
      MonsterGroup = 33,
      MonsterLevel = 108,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.88,
      DefRate = 1,
      LifeRate = 1,
      MAtkRate = 0.88,
      MDefRate = 1,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.94,
      DefRate = 1.06,
      LifeRate = 1.06,
      MAtkRate = 0.94,
      MDefRate = 1.06,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.99,
      DefRate = 1.13,
      LifeRate = 1.13,
      MAtkRate = 0.99,
      MDefRate = 1.13,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.05,
      DefRate = 1.19,
      LifeRate = 1.19,
      MAtkRate = 1.05,
      MDefRate = 1.19,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.25,
      LifeRate = 1.25,
      MAtkRate = 1.1,
      MDefRate = 1.25,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.16,
      DefRate = 1.31,
      LifeRate = 1.31,
      MAtkRate = 1.16,
      MDefRate = 1.31,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.21,
      DefRate = 1.38,
      LifeRate = 1.38,
      MAtkRate = 1.21,
      MDefRate = 1.38,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.27,
      DefRate = 1.44,
      LifeRate = 1.44,
      MAtkRate = 1.27,
      MDefRate = 1.44,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.32,
      DefRate = 1.5,
      LifeRate = 1.5,
      MAtkRate = 1.32,
      MDefRate = 1.5,
      MonsterGroup = 33,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1,
      LifeRate = 1.2,
      MAtkRate = 1,
      MDefRate = 1,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.06,
      DefRate = 1.06,
      LifeRate = 1.28,
      MAtkRate = 1.06,
      MDefRate = 1.06,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.13,
      DefRate = 1.13,
      LifeRate = 1.35,
      MAtkRate = 1.13,
      MDefRate = 1.13,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.19,
      DefRate = 1.19,
      LifeRate = 1.43,
      MAtkRate = 1.19,
      MDefRate = 1.19,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.25,
      DefRate = 1.25,
      LifeRate = 1.5,
      MAtkRate = 1.25,
      MDefRate = 1.25,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.31,
      DefRate = 1.31,
      LifeRate = 1.58,
      MAtkRate = 1.31,
      MDefRate = 1.31,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.38,
      DefRate = 1.38,
      LifeRate = 1.65,
      MAtkRate = 1.38,
      MDefRate = 1.38,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.44,
      DefRate = 1.44,
      LifeRate = 1.73,
      MAtkRate = 1.44,
      MDefRate = 1.44,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.5,
      DefRate = 1.5,
      LifeRate = 1.8,
      MAtkRate = 1.5,
      MDefRate = 1.5,
      MonsterGroup = 33,
      MonsterLevel = 118,
      dam_reduce_type = 7,
      dead_disp_time = 3,
      search = 99
    }
  },
  minitimeline = {
    {10},
    {10, 25},
    {10, 30},
    {
      15,
      30,
      45
    },
    {
      15,
      35,
      55
    },
    {
      10,
      35,
      55
    },
    {
      10,
      35,
      60
    }
  },
  monsterdefine = {
    {
      AtkRate = 0.8,
      DefRate = 1,
      LifeRate = 0.65,
      MAtkRate = 0.8,
      MDefRate = 1,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 0.84,
      DefRate = 1.05,
      LifeRate = 0.68,
      MAtkRate = 0.84,
      MDefRate = 1.05,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 0.88,
      DefRate = 1.1,
      LifeRate = 0.71,
      MAtkRate = 0.88,
      MDefRate = 1.1,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 0.92,
      DefRate = 1.15,
      LifeRate = 0.75,
      MAtkRate = 0.92,
      MDefRate = 1.15,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 0.96,
      DefRate = 1.2,
      LifeRate = 0.78,
      MAtkRate = 0.96,
      MDefRate = 1.2,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1.25,
      LifeRate = 0.81,
      MAtkRate = 1,
      MDefRate = 1.25,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 1.05,
      DefRate = 1.31,
      LifeRate = 0.85,
      MAtkRate = 1.05,
      MDefRate = 1.31,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.38,
      LifeRate = 0.89,
      MAtkRate = 1.1,
      MDefRate = 1.38,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 1.15,
      DefRate = 1.44,
      LifeRate = 0.93,
      MAtkRate = 1.15,
      MDefRate = 1.44,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 1.2,
      DefRate = 1.5,
      LifeRate = 0.97,
      MAtkRate = 1.2,
      MDefRate = 1.5,
      MonsterGroup = 32,
      MonsterLevel = 85,
      search = 99
    },
    {
      AtkRate = 0.8,
      DefRate = 1,
      LifeRate = 0.76,
      MAtkRate = 0.8,
      MDefRate = 1,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 0.84,
      DefRate = 1.05,
      LifeRate = 0.79,
      MAtkRate = 0.84,
      MDefRate = 1.05,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 0.88,
      DefRate = 1.1,
      LifeRate = 0.83,
      MAtkRate = 0.88,
      MDefRate = 1.1,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 0.92,
      DefRate = 1.15,
      LifeRate = 0.87,
      MAtkRate = 0.92,
      MDefRate = 1.15,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 0.96,
      DefRate = 1.2,
      LifeRate = 0.91,
      MAtkRate = 0.96,
      MDefRate = 1.2,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1.25,
      LifeRate = 0.95,
      MAtkRate = 1,
      MDefRate = 1.25,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 1.05,
      DefRate = 1.31,
      LifeRate = 0.99,
      MAtkRate = 1.05,
      MDefRate = 1.31,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.38,
      LifeRate = 1.04,
      MAtkRate = 1.1,
      MDefRate = 1.38,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 1.15,
      DefRate = 1.44,
      LifeRate = 1.09,
      MAtkRate = 1.15,
      MDefRate = 1.44,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 1.2,
      DefRate = 1.5,
      LifeRate = 1.13,
      MAtkRate = 1.2,
      MDefRate = 1.5,
      MonsterGroup = 32,
      MonsterLevel = 100,
      search = 99
    },
    {
      AtkRate = 0.72,
      DefRate = 1,
      LifeRate = 0.72,
      MAtkRate = 0.72,
      MDefRate = 1,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.76,
      DefRate = 1.05,
      LifeRate = 0.76,
      MAtkRate = 0.76,
      MDefRate = 1.05,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.79,
      DefRate = 1.1,
      LifeRate = 0.79,
      MAtkRate = 0.79,
      MDefRate = 1.1,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.83,
      DefRate = 1.15,
      LifeRate = 0.83,
      MAtkRate = 0.83,
      MDefRate = 1.15,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.86,
      DefRate = 1.2,
      LifeRate = 0.86,
      MAtkRate = 0.86,
      MDefRate = 1.2,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.9,
      DefRate = 1.25,
      LifeRate = 0.9,
      MAtkRate = 0.9,
      MDefRate = 1.25,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.95,
      DefRate = 1.31,
      LifeRate = 0.95,
      MAtkRate = 0.95,
      MDefRate = 1.31,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.99,
      DefRate = 1.38,
      LifeRate = 0.99,
      MAtkRate = 0.99,
      MDefRate = 1.38,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 1.04,
      DefRate = 1.44,
      LifeRate = 1.04,
      MAtkRate = 1.04,
      MDefRate = 1.44,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 1.08,
      DefRate = 1.5,
      LifeRate = 1.08,
      MAtkRate = 1.08,
      MDefRate = 1.5,
      MonsterGroup = 32,
      MonsterLevel = 108,
      search = 99
    },
    {
      AtkRate = 0.88,
      DefRate = 1,
      LifeRate = 0.9,
      MAtkRate = 0.88,
      MDefRate = 1,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 0.92,
      DefRate = 1.05,
      LifeRate = 0.95,
      MAtkRate = 0.92,
      MDefRate = 1.05,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 0.97,
      DefRate = 1.1,
      LifeRate = 0.99,
      MAtkRate = 0.97,
      MDefRate = 1.1,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.01,
      DefRate = 1.15,
      LifeRate = 1.04,
      MAtkRate = 1.01,
      MDefRate = 1.15,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.06,
      DefRate = 1.2,
      LifeRate = 1.08,
      MAtkRate = 1.06,
      MDefRate = 1.2,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.25,
      LifeRate = 1.13,
      MAtkRate = 1.1,
      MDefRate = 1.25,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.16,
      DefRate = 1.31,
      LifeRate = 1.18,
      MAtkRate = 1.16,
      MDefRate = 1.31,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.21,
      DefRate = 1.38,
      LifeRate = 1.24,
      MAtkRate = 1.21,
      MDefRate = 1.38,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.27,
      DefRate = 1.44,
      LifeRate = 1.29,
      MAtkRate = 1.27,
      MDefRate = 1.44,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1.32,
      DefRate = 1.5,
      LifeRate = 1.35,
      MAtkRate = 1.32,
      MDefRate = 1.5,
      MonsterGroup = 32,
      MonsterLevel = 113,
      dam_reduce_type = 2,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1,
      LifeRate = 1.08,
      MAtkRate = 1,
      MDefRate = 1,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.05,
      DefRate = 1.05,
      LifeRate = 1.13,
      MAtkRate = 1.05,
      MDefRate = 1.05,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.1,
      LifeRate = 1.19,
      MAtkRate = 1.1,
      MDefRate = 1.1,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.15,
      DefRate = 1.15,
      LifeRate = 1.24,
      MAtkRate = 1.15,
      MDefRate = 1.15,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.2,
      DefRate = 1.2,
      LifeRate = 1.3,
      MAtkRate = 1.2,
      MDefRate = 1.2,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.25,
      DefRate = 1.25,
      LifeRate = 1.35,
      MAtkRate = 1.25,
      MDefRate = 1.25,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.31,
      DefRate = 1.31,
      LifeRate = 1.42,
      MAtkRate = 1.31,
      MDefRate = 1.31,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.38,
      DefRate = 1.38,
      LifeRate = 1.49,
      MAtkRate = 1.38,
      MDefRate = 1.38,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.44,
      DefRate = 1.44,
      LifeRate = 1.55,
      MAtkRate = 1.44,
      MDefRate = 1.44,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    },
    {
      AtkRate = 1.5,
      DefRate = 1.5,
      LifeRate = 1.62,
      MAtkRate = 1.5,
      MDefRate = 1.5,
      MonsterGroup = 32,
      MonsterLevel = 118,
      dam_reduce_type = 5,
      search = 99
    }
  },
  monstertimeline = {
    {
      0,
      5,
      10
    },
    {
      0,
      5,
      10,
      15
    },
    {
      0,
      5,
      10,
      15,
      20
    },
    {
      0,
      5,
      10,
      15,
      20,
      25
    },
    {
      0,
      5,
      10,
      15,
      20,
      25,
      30
    },
    {
      0,
      5,
      10,
      15,
      20,
      25,
      30,
      35
    },
    {
      0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40
    },
    {
      0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45
    },
    {
      0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50
    },
    {
      0,
      5,
      10,
      15,
      20,
      25,
      30,
      35,
      40,
      45,
      50,
      55
    }
  },
  mvpdefine = {
    {
      AtkRate = 0.88,
      DefRate = 1.1,
      LifeRate = 0.79,
      MAtkRate = 0.88,
      MDefRate = 1.1,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.92,
      DefRate = 1.15,
      LifeRate = 0.83,
      MAtkRate = 0.92,
      MDefRate = 1.15,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.96,
      DefRate = 1.2,
      LifeRate = 0.86,
      MAtkRate = 0.96,
      MDefRate = 1.2,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1.25,
      LifeRate = 0.9,
      MAtkRate = 1,
      MDefRate = 1.25,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.04,
      DefRate = 1.3,
      LifeRate = 0.94,
      MAtkRate = 1.04,
      MDefRate = 1.3,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.08,
      DefRate = 1.35,
      LifeRate = 0.97,
      MAtkRate = 1.08,
      MDefRate = 1.35,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.12,
      DefRate = 1.4,
      LifeRate = 1.01,
      MAtkRate = 1.12,
      MDefRate = 1.4,
      MonsterGroup = 34,
      MonsterLevel = 90,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.88,
      DefRate = 1.1,
      LifeRate = 0.92,
      MAtkRate = 0.88,
      MDefRate = 1.1,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.92,
      DefRate = 1.15,
      LifeRate = 0.97,
      MAtkRate = 0.92,
      MDefRate = 1.15,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.96,
      DefRate = 1.2,
      LifeRate = 1.01,
      MAtkRate = 0.96,
      MDefRate = 1.2,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1,
      DefRate = 1.25,
      LifeRate = 1.05,
      MAtkRate = 1,
      MDefRate = 1.25,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.04,
      DefRate = 1.3,
      LifeRate = 1.09,
      MAtkRate = 1.04,
      MDefRate = 1.3,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.08,
      DefRate = 1.35,
      LifeRate = 1.13,
      MAtkRate = 1.08,
      MDefRate = 1.35,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.12,
      DefRate = 1.4,
      LifeRate = 1.18,
      MAtkRate = 1.12,
      MDefRate = 1.4,
      MonsterGroup = 34,
      MonsterLevel = 101,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.79,
      DefRate = 1.1,
      LifeRate = 0.88,
      MAtkRate = 0.79,
      MDefRate = 1.1,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.83,
      DefRate = 1.15,
      LifeRate = 0.92,
      MAtkRate = 0.83,
      MDefRate = 1.15,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.86,
      DefRate = 1.2,
      LifeRate = 0.96,
      MAtkRate = 0.86,
      MDefRate = 1.2,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.9,
      DefRate = 1.25,
      LifeRate = 1,
      MAtkRate = 0.9,
      MDefRate = 1.25,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.94,
      DefRate = 1.3,
      LifeRate = 1.04,
      MAtkRate = 0.94,
      MDefRate = 1.3,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.97,
      DefRate = 1.35,
      LifeRate = 1.08,
      MAtkRate = 0.97,
      MDefRate = 1.35,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.01,
      DefRate = 1.4,
      LifeRate = 1.12,
      MAtkRate = 1.01,
      MDefRate = 1.4,
      MonsterGroup = 34,
      MonsterLevel = 110,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 0.97,
      DefRate = 1.1,
      LifeRate = 1.1,
      MAtkRate = 0.97,
      MDefRate = 1.1,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.01,
      DefRate = 1.15,
      LifeRate = 1.15,
      MAtkRate = 1.01,
      MDefRate = 1.15,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.06,
      DefRate = 1.2,
      LifeRate = 1.2,
      MAtkRate = 1.06,
      MDefRate = 1.2,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.1,
      DefRate = 1.25,
      LifeRate = 1.25,
      MAtkRate = 1.1,
      MDefRate = 1.25,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.14,
      DefRate = 1.3,
      LifeRate = 1.3,
      MAtkRate = 1.14,
      MDefRate = 1.3,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.19,
      DefRate = 1.35,
      LifeRate = 1.35,
      MAtkRate = 1.19,
      MDefRate = 1.35,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.23,
      DefRate = 1.4,
      LifeRate = 1.4,
      MAtkRate = 1.23,
      MDefRate = 1.4,
      MonsterGroup = 34,
      MonsterLevel = 115,
      dam_reduce_type = 3,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.13,
      DefRate = 1.13,
      LifeRate = 1.35,
      MAtkRate = 1.13,
      MDefRate = 1.13,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.16,
      DefRate = 1.16,
      LifeRate = 1.39,
      MAtkRate = 1.16,
      MDefRate = 1.16,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.19,
      DefRate = 1.19,
      LifeRate = 1.43,
      MAtkRate = 1.19,
      MDefRate = 1.19,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.22,
      DefRate = 1.22,
      LifeRate = 1.46,
      MAtkRate = 1.22,
      MDefRate = 1.22,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.25,
      DefRate = 1.25,
      LifeRate = 1.5,
      MAtkRate = 1.25,
      MDefRate = 1.25,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.28,
      DefRate = 1.28,
      LifeRate = 1.54,
      MAtkRate = 1.28,
      MDefRate = 1.28,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    },
    {
      AtkRate = 1.31,
      DefRate = 1.31,
      LifeRate = 1.58,
      MAtkRate = 1.31,
      MDefRate = 1.31,
      MonsterGroup = 34,
      MonsterLevel = 120,
      dam_reduce_type = 10,
      dead_disp_time = 3,
      search = 99
    }
  },
  mvptimeline = {
    {20},
    {35},
    {25, 60},
    {
      20,
      55,
      70
    },
    {
      20,
      60,
      75
    }
  }
}
Table_SpaceTimeIllusionSummon = {
  [1] = {
    totaltime = 45,
    mvpnum = 0,
    mininum = 0,
    monsternum = 30,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[1],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[1]
  },
  [2] = {
    id = 2,
    turn = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 1,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[1],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[1],
    monsternum = 40,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[2],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[2]
  },
  [3] = {
    id = 3,
    turn = 3,
    totaltime = 60,
    mvpnum = 0,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[2],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[2],
    monsternum = 50,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[3],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[3]
  },
  [4] = {
    id = 4,
    turn = 4,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[1],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[1],
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[3],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[3],
    monsternum = 60,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[4],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[4]
  },
  [5] = {
    id = 5,
    turn = 5,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[2],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[2],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[4],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[4],
    monsternum = 70,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[5],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[5]
  },
  [6] = {
    id = 6,
    turn = 6,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[3],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[5],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[5],
    monsternum = 80,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[6],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[6]
  },
  [7] = {
    id = 7,
    turn = 7,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[4],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[6],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[6],
    monsternum = 90,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[7],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[7]
  },
  [8] = {
    id = 8,
    turn = 8,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[4],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[5],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[7],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[8],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[8]
  },
  [9] = {
    id = 9,
    turn = 9,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[6],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[8],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[9],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[9]
  },
  [10] = {
    id = 10,
    turn = 10,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[7],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[9],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[10],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[10]
  },
  [11] = {
    id = 11,
    diff = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 0,
    monsternum = 30,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[1],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[11]
  },
  [12] = {
    id = 12,
    diff = 2,
    turn = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 1,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[1],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[10],
    monsternum = 40,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[2],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[12]
  },
  [13] = {
    id = 13,
    diff = 2,
    turn = 3,
    totaltime = 60,
    mvpnum = 0,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[2],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[11],
    monsternum = 50,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[3],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[13]
  },
  [14] = {
    id = 14,
    diff = 2,
    turn = 4,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[1],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[8],
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[3],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[12],
    monsternum = 60,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[4],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[14]
  },
  [15] = {
    id = 15,
    diff = 2,
    turn = 5,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[2],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[9],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[4],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[13],
    monsternum = 70,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[5],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[15]
  },
  [16] = {
    id = 16,
    diff = 2,
    turn = 6,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[10],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[5],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[14],
    monsternum = 80,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[6],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[16]
  },
  [17] = {
    id = 17,
    diff = 2,
    turn = 7,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[11],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[6],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[15],
    monsternum = 90,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[7],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[17]
  },
  [18] = {
    id = 18,
    diff = 2,
    turn = 8,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[4],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[12],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[16],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[8],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[18]
  },
  [19] = {
    id = 19,
    diff = 2,
    turn = 9,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[13],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[17],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[9],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[19]
  },
  [20] = {
    id = 20,
    diff = 2,
    turn = 10,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[14],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[18],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[10],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[20]
  },
  [21] = {
    id = 21,
    diff = 3,
    totaltime = 45,
    mvpnum = 0,
    mininum = 0,
    monsternum = 30,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[1],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[21]
  },
  [22] = {
    id = 22,
    diff = 3,
    turn = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 1,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[1],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[19],
    monsternum = 40,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[2],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[22]
  },
  [23] = {
    id = 23,
    diff = 3,
    turn = 3,
    totaltime = 60,
    mvpnum = 0,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[2],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[20],
    monsternum = 50,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[3],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[23]
  },
  [24] = {
    id = 24,
    diff = 3,
    turn = 4,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[1],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[15],
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[3],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[21],
    monsternum = 60,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[4],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[24]
  },
  [25] = {
    id = 25,
    diff = 3,
    turn = 5,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[2],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[16],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[4],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[22],
    monsternum = 70,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[5],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[25]
  },
  [26] = {
    id = 26,
    diff = 3,
    turn = 6,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[17],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[5],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[23],
    monsternum = 80,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[6],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[26]
  },
  [27] = {
    id = 27,
    diff = 3,
    turn = 7,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[18],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[6],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[24],
    monsternum = 90,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[7],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[27]
  },
  [28] = {
    id = 28,
    diff = 3,
    turn = 8,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[4],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[19],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[25],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[8],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[28]
  },
  [29] = {
    id = 29,
    diff = 3,
    turn = 9,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[20],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[26],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[9],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[29]
  },
  [30] = {
    id = 30,
    diff = 3,
    turn = 10,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[21],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[27],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[10],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[30]
  },
  [31] = {
    id = 31,
    diff = 4,
    totaltime = 45,
    mvpnum = 0,
    mininum = 0,
    monsternum = 30,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[1],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[31]
  },
  [32] = {
    id = 32,
    diff = 4,
    turn = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 1,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[1],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[28],
    monsternum = 40,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[2],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[32]
  },
  [33] = {
    id = 33,
    diff = 4,
    turn = 3,
    totaltime = 60,
    mvpnum = 0,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[2],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[29],
    monsternum = 50,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[3],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[33]
  },
  [34] = {
    id = 34,
    diff = 4,
    turn = 4,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[1],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[22],
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[3],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[30],
    monsternum = 60,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[4],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[34]
  },
  [35] = {
    id = 35,
    diff = 4,
    turn = 5,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[2],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[23],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[4],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[31],
    monsternum = 70,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[5],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[35]
  },
  [36] = {
    id = 36,
    diff = 4,
    turn = 6,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[24],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[5],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[32],
    monsternum = 80,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[6],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[36]
  },
  [37] = {
    id = 37,
    diff = 4,
    turn = 7,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[25],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[6],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[33],
    monsternum = 90,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[7],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[37]
  },
  [38] = {
    id = 38,
    diff = 4,
    turn = 8,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[4],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[26],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[34],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[8],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[38]
  },
  [39] = {
    id = 39,
    diff = 4,
    turn = 9,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[27],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[35],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[9],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[39]
  },
  [40] = {
    id = 40,
    diff = 4,
    turn = 10,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[28],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[36],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[10],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[40]
  },
  [41] = {
    id = 41,
    diff = 5,
    totaltime = 45,
    mvpnum = 0,
    mininum = 0,
    monsternum = 30,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[1],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[41]
  },
  [42] = {
    id = 42,
    diff = 5,
    turn = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 1,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[1],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[37],
    monsternum = 40,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[2],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[42]
  },
  [43] = {
    id = 43,
    diff = 5,
    turn = 3,
    totaltime = 60,
    mvpnum = 0,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[2],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[38],
    monsternum = 50,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[3],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[43]
  },
  [44] = {
    id = 44,
    diff = 5,
    turn = 4,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[1],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[29],
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[3],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[39],
    monsternum = 60,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[4],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[44]
  },
  [45] = {
    id = 45,
    diff = 5,
    turn = 5,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[2],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[30],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[4],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[40],
    monsternum = 70,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[5],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[45]
  },
  [46] = {
    id = 46,
    diff = 5,
    turn = 6,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[31],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[5],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[41],
    monsternum = 80,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[6],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[46]
  },
  [47] = {
    id = 47,
    diff = 5,
    turn = 7,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[32],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[6],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[42],
    monsternum = 90,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[7],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[47]
  },
  [48] = {
    id = 48,
    diff = 5,
    turn = 8,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[4],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[33],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[43],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[8],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[48]
  },
  [49] = {
    id = 49,
    diff = 5,
    turn = 9,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[34],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[44],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[9],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[49]
  },
  [50] = {
    id = 50,
    diff = 5,
    turn = 10,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[35],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[45],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[10],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[50]
  },
  [51] = {
    id = 51,
    diff = 6,
    totaltime = 45,
    mvpnum = 0,
    mininum = 0,
    monsternum = 30,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[1],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[21]
  },
  [52] = {
    id = 52,
    diff = 6,
    turn = 2,
    totaltime = 45,
    mvpnum = 0,
    mininum = 1,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[1],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[19],
    monsternum = 40,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[2],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[22]
  },
  [53] = {
    id = 53,
    diff = 6,
    turn = 3,
    totaltime = 60,
    mvpnum = 0,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[2],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[20],
    monsternum = 50,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[3],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[23]
  },
  [54] = {
    id = 54,
    diff = 6,
    turn = 4,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[1],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[15],
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[3],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[21],
    monsternum = 60,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[4],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[24]
  },
  [55] = {
    id = 55,
    diff = 6,
    turn = 5,
    totaltime = 90,
    mvpnum = 1,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[2],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[16],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[4],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[22],
    monsternum = 70,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[5],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[25]
  },
  [56] = {
    id = 56,
    diff = 6,
    turn = 6,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[17],
    mininum = 3,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[5],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[23],
    monsternum = 80,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[6],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[26]
  },
  [57] = {
    id = 57,
    diff = 6,
    turn = 7,
    totaltime = 120,
    mvpnum = 2,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[3],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[18],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[6],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[24],
    monsternum = 90,
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[7],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[27]
  },
  [58] = {
    id = 58,
    diff = 6,
    turn = 8,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[4],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[19],
    mininum = 4,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[25],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[8],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[28]
  },
  [59] = {
    id = 59,
    diff = 6,
    turn = 9,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[20],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[26],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[9],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[29]
  },
  [60] = {
    id = 60,
    diff = 6,
    turn = 10,
    mvptimeline = Table_SpaceTimeIllusionSummon_t.mvptimeline[5],
    mvpdefine = Table_SpaceTimeIllusionSummon_t.mvpdefine[21],
    mininum = 5,
    minitimeline = Table_SpaceTimeIllusionSummon_t.minitimeline[7],
    minidefine = Table_SpaceTimeIllusionSummon_t.minidefine[27],
    monstertimeline = Table_SpaceTimeIllusionSummon_t.monstertimeline[10],
    monsterdefine = Table_SpaceTimeIllusionSummon_t.monsterdefine[30]
  }
}
local cell_mt = {
  __index = {
    diff = 1,
    id = 1,
    minidefine = _EmptyTable,
    mininum = 2,
    minitimeline = _EmptyTable,
    monsterdefine = _EmptyTable,
    monsternum = 100,
    monstertimeline = _EmptyTable,
    mvpdefine = _EmptyTable,
    mvpnum = 3,
    mvptimeline = _EmptyTable,
    totaltime = 180,
    turn = 1
  }
}
for _, d in pairs(Table_SpaceTimeIllusionSummon) do
  setmetatable(d, cell_mt)
end
