Table_SpaceTimeIllusionSkills_t = {
  CombineID = {
    {2},
    {3},
    {4},
    {6},
    {7},
    {12},
    {13},
    {14},
    {16},
    {17},
    {22},
    {23},
    {24},
    {26},
    {27},
    {32},
    {33},
    {34},
    {36},
    {37},
    {42},
    {43},
    {44},
    {46},
    {47},
    {52},
    {53},
    {54},
    {56},
    {57},
    {62},
    {63},
    {64},
    {66},
    {67},
    {72},
    {73},
    {74},
    {76},
    {77},
    {82},
    {83},
    {84},
    {86},
    {87},
    {92},
    {93},
    {94},
    {96},
    {97},
    {102},
    {103},
    {104},
    {106},
    {107},
    {112},
    {113},
    {114},
    {116},
    {117},
    {122},
    {123},
    {124},
    {126},
    {127},
    {132},
    {133},
    {134},
    {136},
    {137}
  },
  CurDescVal = {
    {20},
    {5},
    {10, 10},
    {10, 5},
    {2},
    {10},
    {1}
  },
  OverlayBuffs = {
    {313100},
    {313200},
    {313302},
    {315100},
    {315200},
    {315300},
    {315400},
    {316100},
    {316200},
    {316301},
    {317100},
    {317200},
    {317300},
    {318100},
    {318200},
    {318300, 318301},
    {318400, 318401},
    {319002},
    {319100},
    {319200},
    {319300, 319302},
    {319400, 319401},
    {320100},
    {320200},
    {320300},
    {320400},
    {321100},
    {321200},
    {310200},
    {310101},
    {310300},
    {310102},
    {310103},
    {310400},
    {311100},
    {311200},
    {311300},
    {311400},
    {312100},
    {312201},
    {312202},
    {312203},
    {314000},
    {314100},
    {314200, 314201},
    {314200},
    {314300},
    {322100},
    {322200},
    {322300},
    {322400},
    {323100},
    {323200},
    {323300}
  },
  RecommendProfessions = {
    {
      11,
      21,
      22,
      31,
      32,
      41,
      42,
      51,
      52,
      61,
      62,
      71,
      81,
      201,
      211,
      221,
      101,
      111,
      121,
      131,
      601,
      611,
      621,
      631,
      641,
      651,
      661,
      671,
      691,
      701,
      731,
      741,
      751,
      761,
      771
    },
    {
      11,
      21,
      22,
      31,
      41,
      51,
      61,
      101,
      111,
      131,
      671,
      681,
      711,
      721,
      781
    },
    {
      12,
      51,
      71,
      651,
      661
    },
    {
      42,
      51,
      22,
      81,
      611,
      651,
      701,
      741,
      751,
      1000,
      2000
    }
  },
  ReplaceableBuffs = {
    {313000},
    {313300},
    {313400},
    {315000},
    {315301},
    {315401},
    {316000},
    {316300},
    {316400},
    {317000},
    {317400},
    {318000},
    {319000},
    {320000},
    {321000},
    {321300},
    {321400},
    {310000},
    {311000},
    {312000},
    {312300},
    {312400},
    {314010},
    {314400},
    {322000},
    {323000},
    {323400}
  }
}
Table_SpaceTimeIllusionSkills = {
  [1] = {
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[1],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[1],
    SkillAttrDesc = "攻击时，触发一次陨石术，对目标周围造成一次（物理攻击+魔法攻击）*5000%+750000的火属性自适应伤害，并使敌人进入灼烧状态。触发的最短间隔为6秒",
    ShortDesc = "攻击时，触发一次陨石术，触发间隔6秒"
  },
  [2] = {
    id = 2,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[1],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[1],
    SkillAttrDesc = "陨石风暴伤害提升%s%%",
    ShortDesc = "陨石风暴伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [3] = {
    id = 3,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[1],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[2],
    SkillAttrDesc = "自身对灼伤目标伤害增加%s%%",
    ShortDesc = "自身对灼伤目标伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [4] = {
    id = 4,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[1],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[1],
    SkillAttrDesc = "陨石风暴伤害提升%s%%",
    ShortDesc = "陨石风暴伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[1]
  },
  [5] = {
    id = 5,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[2],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[3],
    SkillAttrDesc = "陨石风暴会在敌人脚下留下火柱，火柱每秒造成（物理攻击+魔法攻击）*1000%%+150000的火属性自适应伤害，陨石风暴的触发间隔降低2秒",
    ShortDesc = "陨石风暴会在敌人脚下留下火柱，陨石风暴的触发间隔降低2秒"
  },
  [6] = {
    id = 6,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[2],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[2],
    SkillAttrDesc = "自身对灼伤目标伤害增加%s%%",
    ShortDesc = "自身对灼伤目标伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[2]
  },
  [7] = {
    id = 7,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[2],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[1],
    SkillAttrDesc = "陨石风暴伤害提升%s%%",
    ShortDesc = "陨石风暴伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[3]
  },
  [8] = {
    id = 8,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[2],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[2],
    SkillAttrDesc = "自身对灼伤目标伤害增加%s%%",
    ShortDesc = "自身对灼伤目标伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[4]
  },
  [9] = {
    id = 9,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[2],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[1],
    SkillAttrDesc = "陨石风暴伤害提升%s%%",
    ShortDesc = "陨石风暴伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[5]
  },
  [10] = {
    id = 10,
    SkillID = 84003001,
    NameZh = "陨石风暴",
    Build = "技能、群体",
    Icon = "skill_2711001_1",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[3],
    SkillAttrDesc = "陨石风暴每次触发会释放3次陨石，间隔为0.5秒，陨石风暴的的触发间隔降低2秒",
    ShortDesc = "陨石风暴每次触发会释放3次陨石，陨石风暴的的触发间隔降低2秒"
  },
  [11] = {
    id = 11,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[2],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[4],
    SkillAttrDesc = "普通攻击有25%几率造成撕裂效果，使敌人流血，每秒受到（物理攻击+魔法攻击）*500%+50000的自适应生命流失，持续5秒",
    ShortDesc = "普通攻击有几率造成撕裂效果，使敌人流血"
  },
  [12] = {
    id = 12,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[4],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[4],
    SkillAttrDesc = "撕裂触发几率增加%s%%",
    ShortDesc = "撕裂触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2]
  },
  [13] = {
    id = 13,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[4],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[5],
    SkillAttrDesc = "流血的伤害增加%s%%；对流血状态的敌人造成的伤害增加%s%%",
    ShortDesc = "流血的伤害增加%s%%；对流血状态的敌人造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[3]
  },
  [14] = {
    id = 14,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[4],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[4],
    SkillAttrDesc = "撕裂触发几率增加%s%%",
    ShortDesc = "撕裂触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[6]
  },
  [15] = {
    id = 15,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[5],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[6],
    SkillAttrDesc = "撕裂添加的流血效果可叠加至3层，流血时间+1秒",
    ShortDesc = "撕裂添加的流血效果可叠加至3层，流血时间+1秒"
  },
  [16] = {
    id = 16,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[5],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[5],
    SkillAttrDesc = "流血的伤害增加%s%%；对流血状态的敌人造成的伤害增加%s%%",
    ShortDesc = "流血的伤害增加%s%%；对流血状态的敌人造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[3],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[7]
  },
  [17] = {
    id = 17,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[5],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[4],
    SkillAttrDesc = "撕裂触发几率增加%s%%",
    ShortDesc = "撕裂触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[8]
  },
  [18] = {
    id = 18,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[5],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[5],
    SkillAttrDesc = "流血的伤害增加%s%%；对流血状态的敌人造成的伤害增加%s%%",
    ShortDesc = "流血的伤害增加%s%%；对流血状态的敌人造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[3],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[9]
  },
  [19] = {
    id = 19,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[5],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[4],
    SkillAttrDesc = "撕裂触发几率增加%s%%",
    ShortDesc = "撕裂触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[10]
  },
  [20] = {
    id = 20,
    SkillID = 84005001,
    Build = "普攻、单体",
    Icon = "skill_105190001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[6],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[7],
    SkillAttrDesc = "流血的伤害可以暴击；流血时间+2秒",
    ShortDesc = "流血的伤害可以暴击；流血时间+2秒"
  },
  [21] = {
    id = 21,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[2],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[7],
    SkillAttrDesc = "普通攻击有20%几率附带电流，对目标和其周围3米内最多2个敌人造成（物理攻击+魔法攻击）*3000%+450000的自适应伤害，计算普攻伤害加成和减免；电流的伤害可以暴击；伤害类型为魔法时，会应用法术暴击",
    ShortDesc = "普通攻击有几率附带电流，在目标周围流窜"
  },
  [22] = {
    id = 22,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[7],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[8],
    SkillAttrDesc = "电流触发几率增加%s%%",
    ShortDesc = "电流触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2]
  },
  [23] = {
    id = 23,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[7],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[9],
    SkillAttrDesc = "电流的伤害增加%s%%；电流有%s%%使敌人晕眩3秒",
    ShortDesc = "电流的伤害增加%s%%；电流有%s%%使敌人晕眩3秒",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[4]
  },
  [24] = {
    id = 24,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[7],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[8],
    SkillAttrDesc = "电流触发几率增加%s%%",
    ShortDesc = "电流触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[11]
  },
  [25] = {
    id = 25,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[8],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[10],
    SkillAttrDesc = "电流可命中的敌人数量+2；电流命中的每个敌人使你获得1%攻击速度，持续5秒，最多叠加10层",
    ShortDesc = "电流可命中的敌人数量+2；命中敌人使你增加攻击速度"
  },
  [26] = {
    id = 26,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[8],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[9],
    SkillAttrDesc = "电流的伤害增加%s%%；电流有%s%%使敌人晕眩3秒",
    ShortDesc = "电流的伤害增加%s%%；电流有%s%%使敌人晕眩3秒",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[4],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[12]
  },
  [27] = {
    id = 27,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[8],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[8],
    SkillAttrDesc = "电流触发几率增加%s%%",
    ShortDesc = "电流触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[13]
  },
  [28] = {
    id = 28,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[8],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[9],
    SkillAttrDesc = "电流的伤害增加%s%%；电流有%s%%使敌人晕眩3秒",
    ShortDesc = "电流的伤害增加%s%%；电流有%s%%使敌人晕眩3秒",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[4],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[14]
  },
  [29] = {
    id = 29,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[8],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[8],
    SkillAttrDesc = "电流触发几率增加%s%%",
    ShortDesc = "电流触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[15]
  },
  [30] = {
    id = 30,
    NameZh = "电流链接",
    Icon = "skill_3101001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[9],
    SkillAttrDesc = "电流变为雷暴，会对8米范围内所有敌人造成伤害",
    ShortDesc = "电流变为雷暴，会对8米范围内所有敌人造成伤害"
  },
  [31] = {
    id = 31,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[2],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    SkillAttrDesc = "普通攻击有25%发射3枚追踪弹攻击自身9米范围内的敌人，每枚造成（物理攻击+魔法攻击）*1200%+220000的自适应伤害，弹丸不可命中同一目标，计算普攻伤害加成和减免；弹丸的伤害可以暴击，伤害类型为魔法时，会应用法术暴击",
    ShortDesc = "普通攻击有概率发射3枚追踪弹攻击自身9米范围内的敌人，弹丸不可命中同一目标"
  },
  [32] = {
    id = 32,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[11],
    SkillAttrDesc = "追踪弹伤害增加%s%%",
    ShortDesc = "追踪弹伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [33] = {
    id = 33,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[12],
    SkillAttrDesc = "追踪弹触发几率增加%s%%",
    ShortDesc = "追踪弹触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2]
  },
  [34] = {
    id = 34,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[11],
    SkillAttrDesc = "追踪弹伤害增加%s%%",
    ShortDesc = "追踪弹伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[16]
  },
  [35] = {
    id = 35,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[13],
    SkillAttrDesc = "追踪弹的数量+3；追踪弹命中目标时，使目标的物伤减免减少2%，最多叠加10层",
    ShortDesc = "追踪弹的数量+3；追踪弹命中目标时，使目标的物伤减免减少2%，最多叠加10层"
  },
  [36] = {
    id = 36,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[12],
    SkillAttrDesc = "追踪弹触发几率增加%s%%",
    ShortDesc = "追踪弹触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[17]
  },
  [37] = {
    id = 37,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[11],
    SkillAttrDesc = "追踪弹伤害增加%s%%",
    ShortDesc = "追踪弹伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[18]
  },
  [38] = {
    id = 38,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[12],
    SkillAttrDesc = "追踪弹触发几率增加%s%%",
    ShortDesc = "追踪弹触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[19]
  },
  [39] = {
    id = 39,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[10],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[11],
    SkillAttrDesc = "追踪弹伤害增加%s%%",
    ShortDesc = "追踪弹伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[20]
  },
  [40] = {
    id = 40,
    SkillID = 84007001,
    NameZh = "追踪弹",
    Icon = "skill_1035001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[11],
    SkillAttrDesc = "追踪弹升级为电能追踪弹。命中敌人时，还会埋下电荷种子。拥有电荷的敌人互相靠近时，会触发一次性的自适应风属性伤害，触发之后，电荷种子消失",
    ShortDesc = "追踪弹升级为电能追踪弹。命中敌人时，还会埋下电荷种子。拥有电荷的敌人互相靠近时，会触发一次性的自适应风属性伤害，触发之后，电荷种子消失"
  },
  [41] = {
    id = 41,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[2],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    SkillAttrDesc = "普通攻击有5%概率召唤一把持续10秒的小刀刃，最多召唤5把小刀刃。小刀刃每秒对3m范围敌人造成（物理攻击+魔法攻击）*200%+100000的自适应伤害，计算普攻伤害加成和减免，小刀刃的伤害可以暴击，伤害类型为魔法时，会应用法术暴击",
    ShortDesc = "普通攻击有概率召唤一把持续10秒的小刀刃，最多召唤5把小刀刃。小刀刃每秒对3m范围敌人造成自适应伤害"
  },
  [42] = {
    id = 42,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[14],
    SkillAttrDesc = "召唤小刀刃的概率增加%s%%",
    ShortDesc = "召唤小刀刃的概率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5]
  },
  [43] = {
    id = 43,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[15],
    SkillAttrDesc = "小刀刃的攻击有30%%添加中毒效果，且中毒的伤害提升%s%%",
    ShortDesc = "小刀刃的攻击有30%%添加中毒效果，且中毒的伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [44] = {
    id = 44,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[14],
    SkillAttrDesc = "召唤小刀刃的概率增加%s%%",
    ShortDesc = "召唤小刀刃的概率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[21]
  },
  [45] = {
    id = 45,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[15],
    SkillAttrDesc = "小刀刃的攻击有30%%添加中毒效果，且中毒的伤害提升%s%%",
    ShortDesc = "小刀刃的攻击有30%%添加中毒效果，且中毒的伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [46] = {
    id = 46,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[16],
    SkillAttrDesc = "小刀刃的数量上限提升至10；每拥有一个小刀刃，受到伤害时有2%的概率格挡此次伤害",
    ShortDesc = "小刀刃的数量上限提升至10；每拥有一个小刀刃，受到伤害时有2%的概率格挡此次伤害",
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[22]
  },
  [47] = {
    id = 47,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[14],
    SkillAttrDesc = "召唤小刀刃的概率增加%s%%",
    ShortDesc = "召唤小刀刃的概率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[23]
  },
  [48] = {
    id = 48,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[15],
    SkillAttrDesc = "小刀刃的攻击有30%%添加中毒效果，且中毒的伤害提升%s%%",
    ShortDesc = "小刀刃的攻击有30%%添加中毒效果，且中毒的伤害提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[24]
  },
  [49] = {
    id = 49,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[14],
    SkillAttrDesc = "召唤小刀刃的概率增加%s%%",
    ShortDesc = "召唤小刀刃的概率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[25]
  },
  [50] = {
    id = 50,
    SkillID = 84008001,
    NameZh = "舞动血刃",
    Icon = "skill_6100001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[12],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[17],
    SkillAttrDesc = "每次触发效果会获得两个小刀刃；格挡的概率翻倍",
    ShortDesc = "每次触发效果会获得两个小刀刃；格挡的概率翻倍"
  },
  [51] = {
    id = 51,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[3],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[18],
    SkillAttrDesc = "每次受到伤害后，获得活力再生效果，每秒恢复25000+最大生命值×1%的生命值，持续5秒",
    ShortDesc = "每次受到伤害后，获得活力再生效果，每秒恢复生命值，持续5秒"
  },
  [52] = {
    id = 52,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[19],
    SkillAttrDesc = "活力再生的治疗量提升%s%%",
    ShortDesc = "活力再生的治疗量提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [53] = {
    id = 53,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[20],
    SkillAttrDesc = "活力再生期间，获得%s%%物伤减免和魔伤减免",
    ShortDesc = "活力再生期间，获得%s%%物伤减免和魔伤减免",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [54] = {
    id = 54,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[19],
    SkillAttrDesc = "活力再生的治疗量提升%s%%",
    ShortDesc = "活力再生的治疗量提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[26]
  },
  [55] = {
    id = 55,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[21],
    SkillAttrDesc = "活力再生期间，为周围队友提供每秒恢复最大生命值1%的效果；活力再生可以额外叠加一层",
    ShortDesc = "活力再生期间，为周围队友提供每秒恢复最大生命值1%的效果；活力再生可以额外叠加一层"
  },
  [56] = {
    id = 56,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[20],
    SkillAttrDesc = "活力再生期间，获得%s%%物伤减免和魔伤减免",
    ShortDesc = "活力再生期间，获得%s%%物伤减免和魔伤减免",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[27]
  },
  [57] = {
    id = 57,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[19],
    SkillAttrDesc = "活力再生的治疗量提升%s%%",
    ShortDesc = "活力再生的治疗量提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[28]
  },
  [58] = {
    id = 58,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[20],
    SkillAttrDesc = "活力再生期间，获得%s%%物伤减免和魔伤减免",
    ShortDesc = "活力再生期间，获得%s%%物伤减免和魔伤减免",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[29]
  },
  [59] = {
    id = 59,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[19],
    SkillAttrDesc = "活力再生的治疗量提升%s%%",
    ShortDesc = "活力再生的治疗量提升%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[30]
  },
  [60] = {
    id = 60,
    SkillID = 84009001,
    NameZh = "活力",
    Type = 2,
    Build = "防御",
    Icon = "skill_2311001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[13],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[22],
    SkillAttrDesc = "活力再生期间，为周围队友提供每秒恢复最大生命值5%的效果；活力再生可以额外再叠加一层",
    ShortDesc = "活力再生期间，为周围队友提供每秒恢复最大生命值5%的效果；活力再生可以额外再叠加一层"
  },
  [61] = {
    id = 61,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[3],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    SkillAttrDesc = "受到伤害时，有15%几率生成护盾，可以吸收150000+(物理防御+魔法防御)×20的伤害，持续6秒",
    ShortDesc = "受到伤害时，有几率生成护盾，可以吸收伤害，持续6秒"
  },
  [62] = {
    id = 62,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[23],
    SkillAttrDesc = "元素护盾触发几率增加%s%%",
    ShortDesc = "元素护盾触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2]
  },
  [63] = {
    id = 63,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[24],
    SkillAttrDesc = "元素护盾的护盾量增加%s%%",
    ShortDesc = "元素护盾的护盾量增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [64] = {
    id = 64,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[23],
    SkillAttrDesc = "元素护盾触发几率增加%s%%",
    ShortDesc = "元素护盾触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[31]
  },
  [65] = {
    id = 65,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[25],
    SkillAttrDesc = "元素护盾可以额外叠加一层；护盾被击破或者到期时，对周围3米内的敌人造成1250000+(物理防御+魔法防御）×75的自适应伤害",
    ShortDesc = "元素护盾可以额外叠加一层；护盾被击破或者到期时，对周围3米内的敌人造成自适应伤害"
  },
  [66] = {
    id = 66,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[24],
    SkillAttrDesc = "元素护盾的护盾量增加%s%%",
    ShortDesc = "元素护盾的护盾量增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[32]
  },
  [67] = {
    id = 67,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[23],
    SkillAttrDesc = "元素护盾触发几率增加%s%%",
    ShortDesc = "元素护盾触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[33]
  },
  [68] = {
    id = 68,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[24],
    SkillAttrDesc = "元素护盾的护盾量增加%s%%",
    ShortDesc = "元素护盾的护盾量增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[34]
  },
  [69] = {
    id = 69,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[23],
    SkillAttrDesc = "元素护盾触发几率增加%s%%",
    ShortDesc = "元素护盾触发几率增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[2],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[35]
  },
  [70] = {
    id = 70,
    SkillID = 84010001,
    NameZh = "元素护盾",
    Type = 2,
    Build = "防御",
    Icon = "skill_79305001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[14],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[26],
    SkillAttrDesc = "元素护盾存在期间，获得50%最终伤害减免",
    ShortDesc = "元素护盾存在期间，获得50%最终伤害减免"
  },
  [71] = {
    id = 71,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[4],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[15],
    SkillAttrDesc = "光环效果；每2秒为周围5米内的队友恢复15000+(智力+体质)×20的生命值",
    ShortDesc = "光环效果；每2秒为周围5米内的队友恢复生命值"
  },
  [72] = {
    id = 72,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[15],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[27],
    SkillAttrDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    ShortDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [73] = {
    id = 73,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[15],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[28],
    SkillAttrDesc = "治愈光环的治疗量增加%s%%",
    ShortDesc = "治愈光环的治疗量增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [74] = {
    id = 74,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[15],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[27],
    SkillAttrDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    ShortDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[36]
  },
  [75] = {
    id = 75,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[16],
    SkillAttrDesc = "治愈光环的半径+2米；治愈光环对50%%血量一下队友治疗量翻倍，并恢复目标1%的最大法力值",
    ShortDesc = "治愈光环的半径+2米；治愈光环对50%%血量一下队友治疗量翻倍，并恢复目标1%的最大法力值"
  },
  [76] = {
    id = 76,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[16],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[28],
    SkillAttrDesc = "治愈光环的治疗量增加%s%%",
    ShortDesc = "治愈光环的治疗量增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[37]
  },
  [77] = {
    id = 77,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[16],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[27],
    SkillAttrDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    ShortDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[38]
  },
  [78] = {
    id = 78,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[16],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[28],
    SkillAttrDesc = "治愈光环的治疗量增加%s%%",
    ShortDesc = "治愈光环的治疗量增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[39]
  },
  [79] = {
    id = 79,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[16],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[27],
    SkillAttrDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    ShortDesc = "光环效果下的队友受到的治疗效果增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[40]
  },
  [80] = {
    id = 80,
    SkillID = 84011001,
    NameZh = "治愈光环",
    Type = 3,
    Build = "辅助",
    Icon = "skill_106505001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[17],
    SkillAttrDesc = "治愈光环的触发间隔降低至1秒；治愈光环每隔3秒还会清除一次队友的负面效果",
    ShortDesc = "治愈光环的触发间隔降低至1秒；治愈光环每隔3秒还会清除一次队友的负面效果"
  },
  [81] = {
    id = 81,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[1],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    SkillAttrDesc = "每次使用技能时，释放一颗奥术飞弹，对半径6米内随机一名敌人造成（物理攻击+魔法攻击）*1500%+200000的无属性自适应伤害，会优先攻击血量百分比最低的敌人",
    ShortDesc = "每次使用技能时，对周围一名敌人释放一颗奥术飞弹,会优先攻击血量百分比最低的敌人"
  },
  [82] = {
    id = 82,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[29],
    SkillAttrDesc = "【奥术飞弹】伤害增加%s%%",
    ShortDesc = "【奥术飞弹】伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [83] = {
    id = 83,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[30],
    SkillAttrDesc = "【奥术飞弹】飞弹数量+%s",
    ShortDesc = "【奥术飞弹】飞弹数量+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7]
  },
  [84] = {
    id = 84,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[29],
    SkillAttrDesc = "【奥术飞弹】伤害增加%s%%",
    ShortDesc = "【奥术飞弹】伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[41]
  },
  [85] = {
    id = 85,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[31],
    SkillAttrDesc = "【奥术飞弹】奥术飞弹会发射两波飞弹",
    ShortDesc = "【奥术飞弹】奥术飞弹会发射两波飞弹"
  },
  [86] = {
    id = 86,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[32],
    SkillAttrDesc = "【奥术飞弹】飞弹数量+%s",
    ShortDesc = "【奥术飞弹】飞弹数量+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[42]
  },
  [87] = {
    id = 87,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[29],
    SkillAttrDesc = "【奥术飞弹】伤害增加%s%%",
    ShortDesc = "【奥术飞弹】伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[43]
  },
  [88] = {
    id = 88,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[33],
    SkillAttrDesc = "【奥术飞弹】飞弹数量+%s",
    ShortDesc = "【奥术飞弹】飞弹数量+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[44]
  },
  [89] = {
    id = 89,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[29],
    SkillAttrDesc = "【奥术飞弹】伤害增加%s%%",
    ShortDesc = "【奥术飞弹】伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[45]
  },
  [90] = {
    id = 90,
    SkillID = 84000001,
    NameZh = "奥术飞弹",
    Build = "技能、单体",
    Icon = "skill_105910001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[18],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[34],
    SkillAttrDesc = "【奥术飞弹】造成伤害翻倍，如果敌人血量低于50%，则再翻一倍",
    ShortDesc = "【奥术飞弹】造成伤害翻倍，如果敌人血量低于50%，则再翻一倍"
  },
  [91] = {
    id = 91,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[1],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    SkillAttrDesc = "释放单体技能时，获得一层元素专注，持续10秒；每层元素专注能使单体技能暴击概率+1%，暴击时，造成200%伤害，最多叠加10层；元素专注的效果和其他技能类的暴击效果可以叠加",
    ShortDesc = "释放单体技能时，获得一层元素专注；每层元素专注能使单体技能暴击概率+1%，暴击时，造成200%%伤害，最多叠加10层；"
  },
  [92] = {
    id = 92,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[35],
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [93] = {
    id = 93,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[36],
    SkillAttrDesc = "元素专注满层时，单体技能的暴击率额外增加%s%%",
    ShortDesc = "元素专注满层时，单体技能的暴击率额外增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [94] = {
    id = 94,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[35],
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[46]
  },
  [95] = {
    id = 95,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[37],
    SkillAttrDesc = "单体技能暴击时，增加自身2%的物理、魔法穿刺，最多叠加10层",
    ShortDesc = "单体技能暴击时，增加自身2%的物理、魔法穿刺，最多叠加10层"
  },
  [96] = {
    id = 96,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[36],
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[47]
  },
  [97] = {
    id = 97,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[35],
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[48]
  },
  [98] = {
    id = 98,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[36],
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[49]
  },
  [99] = {
    id = 99,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[35],
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[50]
  },
  [100] = {
    id = 100,
    SkillID = 84001001,
    NameZh = "元素专注",
    Build = "技能、单体",
    Icon = "skill_3312001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[19],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[38],
    SkillAttrDesc = "单体技能暴击时，对目标额外造成一次（物理攻击+魔法攻击）*3000%+500000的自适应伤害",
    ShortDesc = "单体技能暴击时，对目标额外造成一次自适应伤害"
  },
  [101] = {
    id = 101,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[1],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[20],
    SkillAttrDesc = "施放群体技能时，目的地处触发一次元素风暴，对半径4米内所有敌人造成（物理攻击+魔法攻击）*1000%+150000的4次属性不同的自适应伤害",
    ShortDesc = "施放群体技能时，目的地处触发一次元素风暴，对周围敌人造成4次属性不同的自适应伤害"
  },
  [102] = {
    id = 102,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[20],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[39],
    SkillAttrDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    ShortDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [103] = {
    id = 103,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[20],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[40],
    SkillAttrDesc = "元素风暴的半径增加%s米",
    ShortDesc = "元素风暴的半径增加%s米",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7]
  },
  [104] = {
    id = 104,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[20],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[39],
    SkillAttrDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    ShortDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[51]
  },
  [105] = {
    id = 105,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[21],
    SkillAttrDesc = "元素风暴变为持续效果，总共会造成3次伤害",
    ShortDesc = "元素风暴变为持续效果，总共会造成3次伤害"
  },
  [106] = {
    id = 106,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[21],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[41],
    SkillAttrDesc = "元素风暴的半径增加%s米",
    ShortDesc = "元素风暴的半径增加%s米",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[52]
  },
  [107] = {
    id = 107,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[21],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[39],
    SkillAttrDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    ShortDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[53]
  },
  [108] = {
    id = 108,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[21],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[42],
    SkillAttrDesc = "元素风暴的半径增加%s米",
    ShortDesc = "元素风暴的半径增加%s米",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[54]
  },
  [109] = {
    id = 109,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[21],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[39],
    SkillAttrDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    ShortDesc = "元素风暴对拥有护盾目标造成的伤害增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[55]
  },
  [110] = {
    id = 110,
    SkillID = 84002001,
    NameZh = "能量风暴",
    Build = "技能、群体",
    Icon = "skill_4510001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[22],
    SkillAttrDesc = "每次额外生成一个元素风暴",
    ShortDesc = "每次额外生成一个元素风暴"
  },
  [111] = {
    id = 111,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[2],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[43],
    SkillAttrDesc = "每次普通攻击增加一层连击层数，最多10层。每层提升3%攻击速度和5%伤害，这部分攻速可以突破攻速上限。普通攻击切换目标时，层数会全部清空。",
    ShortDesc = "每次普通攻击增加一层连击层数，最多10层。每层提升攻击速度和伤害。普通攻击切换目标时，层数会全部清空。"
  },
  [112] = {
    id = 112,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[44],
    SkillAttrDesc = "连击的层数上限+%s",
    ShortDesc = "连击的层数上限+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5]
  },
  [113] = {
    id = 113,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[45],
    SkillAttrDesc = "连击层数在10层以上时，普通攻击有%s%%概率额外攻击一次",
    ShortDesc = "连击层数在10层以上时，普通攻击有%s%%概率额外攻击一次",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [114] = {
    id = 114,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[44],
    SkillAttrDesc = "连击的层数上限+%s",
    ShortDesc = "连击的层数上限+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[56]
  },
  [115] = {
    id = 115,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[46],
    SkillAttrDesc = "有相同概率触发第二次额外攻击",
    ShortDesc = "有相同概率触发第二次额外攻击"
  },
  [116] = {
    id = 116,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[47],
    SkillAttrDesc = "连击层数在10层以上时，普通攻击有%s%%概率额外攻击一次",
    ShortDesc = "连击层数在10层以上时，普通攻击有%s%%概率额外攻击一次",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[57]
  },
  [117] = {
    id = 117,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[44],
    SkillAttrDesc = "连击的层数上限+%s",
    ShortDesc = "连击的层数上限+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[58]
  },
  [118] = {
    id = 118,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[46],
    SkillAttrDesc = "连击层数在10层以上时，普通攻击有%s%%概率额外攻击一次",
    ShortDesc = "连击层数在10层以上时，普通攻击有%s%%概率额外攻击一次",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[59]
  },
  [119] = {
    id = 119,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[23],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[44],
    SkillAttrDesc = "连击的层数上限+%s",
    ShortDesc = "连击的层数上限+%s",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[5],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[60]
  },
  [120] = {
    id = 120,
    SkillID = 84004001,
    NameZh = "连击",
    Build = "普攻、单体",
    Icon = "skill_179001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[24],
    SkillAttrDesc = "切换目标时，连击层数不再衰减",
    ShortDesc = "切换目标时，连击层数不再衰减"
  },
  [121] = {
    id = 121,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[4],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    SkillAttrDesc = "对队友溢出的治疗量可以转化成护盾，护盾最大值为自身生命上限的20%+200000",
    ShortDesc = "对队友溢出的治疗量可以转化成护盾，护盾最大值为自身生命上限的20%+200000"
  },
  [122] = {
    id = 122,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[48],
    SkillAttrDesc = "自身的治疗加成+%s%%",
    ShortDesc = "自身的治疗加成+%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1]
  },
  [123] = {
    id = 123,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[49],
    SkillAttrDesc = "守护之盾的护盾值上限增加%s%%",
    ShortDesc = "守护之盾的护盾值上限增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [124] = {
    id = 124,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[48],
    SkillAttrDesc = "自身的治疗加成+%s%%",
    ShortDesc = "自身的治疗加成+%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[61]
  },
  [125] = {
    id = 125,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[50],
    SkillAttrDesc = "守护之盾存在时，提供10%的最终伤害减免",
    ShortDesc = "守护之盾存在时，提供10%的最终伤害减免"
  },
  [126] = {
    id = 126,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[49],
    SkillAttrDesc = "守护之盾的护盾值上限增加%s%%",
    ShortDesc = "守护之盾的护盾值上限增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[62]
  },
  [127] = {
    id = 127,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[48],
    SkillAttrDesc = "自身的治疗加成+%s%%",
    ShortDesc = "自身的治疗加成+%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[63]
  },
  [128] = {
    id = 128,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[49],
    SkillAttrDesc = "守护之盾的护盾值上限增加%s%%",
    ShortDesc = "守护之盾的护盾值上限增加%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[64]
  },
  [129] = {
    id = 129,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[48],
    SkillAttrDesc = "自身的治疗加成+%s%%",
    ShortDesc = "自身的治疗加成+%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[1],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[65]
  },
  [130] = {
    id = 130,
    SkillID = 84012001,
    NameZh = "守护之盾",
    Type = 3,
    Build = "辅助",
    Icon = "skill_1181001",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[25],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[51],
    SkillAttrDesc = "守护之盾存在时，提供20%的最终伤害减免和20%的物伤加成和魔伤加成",
    ShortDesc = "守护之盾存在时，提供20%的最终伤害减免和20%的物伤加成和魔伤加成"
  },
  [131] = {
    id = 131,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    RecommendProfessions = Table_SpaceTimeIllusionSkills_t.RecommendProfessions[4],
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    SkillAttrDesc = "光环效果；对半径4米最近目标施加虚弱诅咒，降低其20%的物理和魔法攻击",
    ShortDesc = "光环效果；对半径4米最近目标施加虚弱诅咒，降低其20%的物理和魔法攻击"
  },
  [132] = {
    id = 132,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 2,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[52],
    SkillAttrDesc = "受诅咒敌人的移动速度降低%s%%",
    ShortDesc = "受诅咒敌人的移动速度降低%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6]
  },
  [133] = {
    id = 133,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 3,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[53],
    SkillAttrDesc = "虚弱诅咒的半径增加%s米",
    ShortDesc = "虚弱诅咒的半径增加%s米",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7]
  },
  [134] = {
    id = 134,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 4,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[52],
    SkillAttrDesc = "受诅咒敌人的移动速度降低%s%%",
    ShortDesc = "受诅咒敌人的移动速度降低%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[66]
  },
  [135] = {
    id = 135,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 5,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[54],
    SkillAttrDesc = "受诅咒敌人攻击时有10%概率丢失",
    ShortDesc = "受诅咒敌人攻击时有10%概率丢失"
  },
  [136] = {
    id = 136,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 6,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[53],
    SkillAttrDesc = "虚弱诅咒的半径增加%s米",
    ShortDesc = "虚弱诅咒的半径增加%s米",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[67]
  },
  [137] = {
    id = 137,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 7,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[52],
    SkillAttrDesc = "受诅咒敌人的移动速度降低%s%%",
    ShortDesc = "受诅咒敌人的移动速度降低%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[68]
  },
  [138] = {
    id = 138,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 8,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[53],
    SkillAttrDesc = "虚弱诅咒的半径增加%s米",
    ShortDesc = "虚弱诅咒的半径增加%s米",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[7],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[69]
  },
  [139] = {
    id = 139,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 9,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[26],
    OverlayBuffs = Table_SpaceTimeIllusionSkills_t.OverlayBuffs[52],
    SkillAttrDesc = "受诅咒敌人的移动速度降低%s%%",
    ShortDesc = "受诅咒敌人的移动速度降低%s%%",
    CurDescVal = Table_SpaceTimeIllusionSkills_t.CurDescVal[6],
    CombineID = Table_SpaceTimeIllusionSkills_t.CombineID[70]
  },
  [140] = {
    id = 140,
    SkillID = 84013001,
    NameZh = "虚弱诅咒",
    Type = 3,
    Build = "辅助",
    SkillLevel = 10,
    ReplaceableBuffs = Table_SpaceTimeIllusionSkills_t.ReplaceableBuffs[27],
    SkillAttrDesc = "虚弱诅咒变为群体诅咒，影响自己周围7米内的所有敌人，但效果降低为原来的75%；受诅咒敌人攻击时有20%概率丢失",
    ShortDesc = "虚弱诅咒变为群体诅咒，影响自己周围7米内的所有敌人，但效果降低为原来的75%；受诅咒敌人攻击时有20%概率丢失"
  }
}
local cell_mt = {
  __index = {
    Build = "普攻、群体",
    CombineID = _EmptyTable,
    CurDescVal = _EmptyTable,
    Icon = "skill_103250001",
    NameZh = "撕裂",
    OverlayBuffs = _EmptyTable,
    RecommendProfessions = _EmptyTable,
    ReplaceableBuffs = _EmptyTable,
    ShortDesc = "元素专注满层时，单体技能的暴击伤害增加%s%%",
    SkillAttrDesc = "元素专注满层时，单体技能的暴击伤害增加%s%%",
    SkillID = 84006001,
    SkillLevel = 1,
    Type = 1,
    id = 1
  }
}
for _, d in pairs(Table_SpaceTimeIllusionSkills) do
  setmetatable(d, cell_mt)
end
